### ISSUE TITLE
Problem in Chrome, wenn Player aus Seite entfernt und neuer eingefügt wird

### ISSUE THREAD

**Issue by BitScout** [podlove/podlove-web-player#141]
Kategorie: Bug / You're holding it wrong

Beispielseite: http://podcastradio.org/station.html#42
Funktioniert in Firefox, in Chrome nur bis zum ersten Episodenübergang.

Bei Betätigen von "Skip" oder nach Ende der Episode wird der Player im DOM durch ein neues Audio-Element ersetzt (Selektor: "div#playercontainer :first-child"). Danach wird aus diesem neuen Audio-Element ein neuer PWP erstellt. Ziel der Aktion ist es, eine neue Medien-URL "einzulegen" und mit der Wiedergabe zu beginnen.

In Firefox funktioniert die Aktion wie gewünscht, in Chrome unter Windows erscheint die Player-Oberfläche leicht zerschossen (Lautstärkeregler baumelt links unten) und die Wiedergabe erfolgt nicht.

Der entscheidende Codeabschnitt liegt in Funktion setEpisode() in folgendem JS-File:
http://podcastradio.org/js/podcastradio.js

**Comment by line-o** [comment]
Es geht dir also darum mehrere Episoden mit derselben Playerinstanz abzuspielen.
Die kommende Version des Players (3.0) wir per Iframe eingebunden. 
Dem einbindenden Skript (moderator) sollte es möglich sein eine neue URL (Episode) zu übergeben.
Allerdings wäre das nicht über einen Skip-Button im Player selbst zu steuern. 
Derzeit wäre es lediglich beim Ende einer Episode möglich in der Seite eine JS-Funktion des Nutzers aufzurufen. Wäre das für dich eine Lösung?

**Comment by BitScout** [comment]
Ja, das war mein Ziel. Inzwischen habe ich das Problem umgangen, indem ich die Seite mit dem Player komplett neu lade, siehe http://podcastrad.io - Das Vermeiden von Episoden-Wiederholungen mache ich jetzt über localStorage.
