### ISSUE TITLE
optimize css cursor in volume control

### ISSUE THREAD

**Issue by HolgerJeromin** [podlove/podlove-web-player#142]
right now there is a css

```
cursor:move;
```

on the volume and play position control. In my opinion a 

```
cursor:ew-resize;
```

would be a better choice or with a fallback 

```
cursor:ew-resize, move;
```

Browser support ist quite good:
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by HolgerJeromin** [comment]
Is this fixed?

**Comment by alexander-heimbuch** [comment]
Podlove Player v2 and v3 are in maintenance mode. This repo now represents v4. If the fix isn't already in v3 or v2 it won't be fixed.
