### ISSUE TITLE
Player Styling doesn't have any effect.

### ISSUE THREAD

**Issue by chrismarquardt** [podlove/podlove-web-player#143]
I have changed the player style for www.tipsfromthetopfloor.com but that doesn't seem to have any effect. I tried with both the enclosures option and the shortcodes. The player doesn't change.

Podlove Web Player v 2.0.19

![podlove_style_bug-4](https://f.cloud.github.com/assets/2527608/2060535/2e5e1eb4-8c20-11e3-8a1b-4f206c3768de.jpg)

**Comment by line-o** [comment]
Sorry. This feature is deprecated and will be solved in a completely different and likely better way in the upcoming version of the player.
