### ISSUE TITLE
Podlove Standalone-Player zeigt letztes Kapitel nur halbe Zeile

### ISSUE THREAD

**Issue by Meiky** [podlove/podlove-web-player#175]
Hallo, ich nutzen nun den Standalone Webplayer von Podlove. Aber das letzte Kapitel wird immer nur als halbe Zeile angezeigt, wenn ich den Shortcode eingebaut habe.
Hab schon viel probiert, es wird nur als ganze Zeile anzeigt, wenn ich alles aus dem Code rausnehme und nur noch die Kapitel drin lasse (was ja nicht Sinn der Sache ist) In den WP Einstellungen, hab ich auch nichts angegeben, damit die Kapitel komplett angezeigt werden. Muss nun aber einen Wert eingeben, damit der Scrollbalken, eben für die letzte Zeile da ist.
Wobei, es völlig egal ist, was für einen Wert ich angebe, die Zeile ist immer nur halb zu sehen.
Der Player klappt da einfach nicht ganz auf.

Eingebaut sind die Kapitel über WP Benutzerdefiniertes Feld, alles die neuesten Versionen.

Ist das vielleicht ein Bug, oder mach ich was falsch?

**Comment by line-o** [comment]
Will close this for now.
