### ISSUE TITLE
Podlove does not work on Opera

### ISSUE THREAD

**Issue by namtrung** [podlove/podlove-web-player#178]
I've just tested with Opera 24, however Podlove does not work:
http://cms.page-flex.com/shortcode-media-player

**Comment by plutonik-a** [comment]
Hi Namtrung,

I can't even open your link in __any__ browser.
Can you please describe your problem in a way, that we are able to reproduce the bug/problem and tell us under what circumstances or environment it occurs or doesn't?

**Comment by timpritlove** [comment]
There is no A or AAA record for cms.page-flex.com. Please give us a proper URL that works to test.
