### ISSUE TITLE
[wish] Im popup abspielen 

### ISSUE THREAD

**Issue by sethiele** [podlove/podlove-web-player#224]
Es wäre sicherlich eine super funktioniert, wenn der Player die Möglichkeit bieten würde sich selbst (nur den player) als popup zu öffnen. Dann könnten Zuhörer wie gewohnt surfen ohne die Wiedergabe zu unterbrechen, wenn man doch mal den falschen Tab schließt, oder einem [Link in den shownotes folgt](https://sendegate.de/t/target--blank-an-links-anhangen/896). 

Ich hätte es mir so gedacht, das der Player dafür einen eigenen Button anbietet. Und am besten sollte die Wiedergabe an der aktuellen Stelle weitergeführt werden und der Player (von dem der Aufruf kommt) sollte anhalten.

**Comment by line-o** [comment]
Yep. That feature is on our list.
