### ISSUE TITLE
Download Button funktioniert nicht in Thunderbrowse

### ISSUE THREAD

**Issue by JPRuehmann** [podlove/podlove-web-player#225]
Hallo
Wenn ich auf den Download Button im WebPlayer klicke passiert nichts.
Um einen Podcast Downzuloaden muß ich auf URL anzeigen klicken, die URL markieren, die URL kopieren, den Download Manager öfnen, Die URL markieren und den Download starten.
Das ist bei allen Podcasts die Podlove benutzen so, alle anderen podcasts funktionieren normal, Download anklicken bestätigen und los geht es.

Ich benutze Kubuntu 14.04 (LTS) Thunderbird 31, Thunderbrowse 3.82, Java 9, Flash 11.2.220.440.

Danke,
JPR

**Comment by timpritlove** [comment]
Definiere "passiert nichts" bitte.

Gibt es in Deinem JavaScript Log irgendwelche Meldungen in dem Moment?

**Comment by JPRuehmann** [comment]
Nein
Nur die Button Grafik wechselt.
