### ISSUE TITLE
Expand chapter list on play

### ISSUE THREAD

**Issue by nkali** [podlove/podlove-web-player#226]
The default player with its chapter list hidden is compact and looks nice.

However, users who do not know of the possibility that there might be chapters often will not press the chapter button. On the other hand, showing the player with expanded chapter list by default uses a lot of space.

A solution would be to expand the chapter fields once the user presses Play. Is this possible? If not, this would be useful to have as an optional feature, specifically in the Wordpress shortcode.

**Comment by line-o** [comment]
Unfortunately, @nkali this is not yet possible. As this is an interesting feature we will think about adding it to an upcoming release.

**Comment by nkali** [comment]
Thanks! I'm sure this would be a welcome addition.

**Comment by Inrumpo** [comment]
+1 

I'd love to see that feature!

**Comment by line-o** [comment]
You can achieve what you want with the upcoming version 3.
Please have a look at the example player on http://sourcerer.org/ if that is the feature you were looking for.
