### ISSUE TITLE
Tooltips being displayed

### ISSUE THREAD

**Issue by stephenthor** [podlove/podlove-web-player#227]
Not sure what is going on here. It was working totally fine until I updated wordpress a while back. 

![image](https://cloud.githubusercontent.com/assets/10951928/6141213/5c566db4-b170-11e4-9de3-e85b4fcde713.png)

**Comment by stephenthor** [comment]
Here's a link to the page
http://victorypsu.org/vcf/portfolio-item/bad-church-experience/

**Comment by chemiker** [comment]
Hey stephenthor,

could you paste a list of your WordPress plugins installed and activated? This will help us to reproduce the issue :)

**Comment by stephenthor** [comment]
![image](https://cloud.githubusercontent.com/assets/10951928/6287558/726b0d2c-b8e0-11e4-964e-e6f593aa7546.png)
![image](https://cloud.githubusercontent.com/assets/10951928/6287572/8eda3fdc-b8e0-11e4-9b5c-756ecf13f413.png)
![image](https://cloud.githubusercontent.com/assets/10951928/6287583/9e144d1c-b8e0-11e4-8695-02be54f346bc.png)

**Comment by stephenthor** [comment]
Any ideas?

**Comment by line-o** [comment]
Unfortunately, the list of installed plugins does not reveal anything. Wordpress now includes a version of Mediaelement.js which might collide with the one used by the podlove-web-player.

**Comment by line-o** [comment]
The page in question is no longer online. Closing this issue for now.
