### ISSUE TITLE
Podlove Web Player issue.

### ISSUE THREAD

**Issue by alexridley** [podlove/podlove-web-player#230]
So this isn't going to be very useful, but I had the web player working and then one day it just stopped. I didn't change anything that I'm aware of and have no idea where to begin to look. I didn't update anything at all either.

Does this sound familiar to anyone? Does anyone know where to possibly look / what to do?

**Comment by line-o** [comment]
If your problem still exists could you provide further details? Your setup, versions and a link to the page.

**Comment by line-o** [comment]
Due to inactivity.
