### ISSUE TITLE
CURLOPT_FOLLOWLOCATION cannot be activated when in safe_mode or an open_basedir is set

### ISSUE THREAD

**Issue by argl** [podlove/podlove-web-player#236]
I ran into this on a shared host where I cannot disable open_basedir. It comes up when saving an Episode. Since I am not really on top of PHP these days, is this setting an ancient relict of a long gone time when "safe_mode" ruled the world?

I guess podlove needs proper redirects working at least when analytics are enabled. Is it necessary to implement redirect following in PHP like some people suggest as a workaround?

**Comment by eteubert** [comment]
It's a known issue to the Publisher:

- http://stackoverflow.com/questions/2511410/curl-follow-location-error1
- http://stackoverflow.com/questions/19539922/php-can-curlopt-followlocation-and-open-basedir-be-used-together4

> I ran into this on a shared host where I cannot disable open_basedir

Can't access the apache conf? http://stackoverflow.com/a/223834/72448 

> I guess podlove needs proper redirects working at least when analytics are enabled.

Correct

> Is it necessary to implement redirect following in PHP like some people suggest as a workaround?

I'm not sure. There is no viable alternative to curl and the workarounds I know of are ugly/hacky. I also expect the problem to disappear in the near future since shared hosting is getting replaced by cheap containerized / VPS hosting, and this kind of hosting has no need for open_basedir.

**Comment by eteubert** [comment]
Although I'm not sure what exactly causes this, since we _are_ checking for it: https://github.com/podlove/podlove-publisher/blob/master/lib/model/media_file.php#L331

**Comment by argl** [comment]
Hm, good catch. The value is actually checked. I dug a little deeper and got stumped, ```ini_get()``` does not seem to return the ```open_basedir``` setting. I checked with thefollowing code:

```php
<pre>
<?php
echo 'allow_url_fopen = ' . ini_get('allow_url_fopen') . "\n";
echo 'open_basedir = ' . ini_get('open_basedir') . "\n";
?>
</pre>

<pre>
<?php
  print_r(ini_get_all(null, false));
?>
</pre>
```

The output is:
```
allow_url_fopen = 1
open_basedir = 
Array
(
    [allow_url_fopen] => 1
..loads of settings...
    [open_basedir] => /tmp:/home2/www/webmailredirect
)
```

So, ```ini_get_all()``` shows me the correct value, and ```ini_get()``` does not. I am aware that this does not seem to be a podlove publisher problem, but I do not understand that behaviour. Please feel free to close this issue.

**Comment by argl** [comment]
I worked around the problem for now by disabling all error reporting (```error_reporting(0)```), so the warning does not make it to the output. Still, I am puzzled.

**Comment by chemiker** [comment]
Could you instead of echo ini_get('open_basedir') use var_dump() and paste the output here?

**Comment by argl** [comment]
sure.

```php
var_dump(ini_get('open_basedir'));
```
result:
```
string(0) ""
```

**Comment by line-o** [comment]
could we move this issue to podlove/podlove-publisher ?

**Comment by argl** [comment]
oops, silly me, I did not notice that I was in the wrong building. Sorry.
