### ISSUE TITLE
[Request] Force to hide Summary-Info-Button

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-web-player#239]
Hello community & developers

I have a minor request:
There is a "hide time buttons" option in Settings > Podlove Web Player > Buttons as well as a "Hide share buttons" option. I like that.
Please add this option for the Summary-Info-Button too. I know that - as mentioned within the options menu - this button will be hidden if there is no summary. But I d'like to hide it even if there is a summary.
Why? Podcatchers display the summary - so I need/want one. But I don't need that summary visible on my podcast homepage where I have the complete shownotes.

**Comment by Inrumpo** [comment]
As a temporary solution, I tried the following in my stylesheet.css:

    a.infowindow.infobuttons.pwp-icon-info-circle {
      display: none;
    }

Unfortunately, this has no effect.

**Comment by plutonik-a** [comment]
Sorry, but we won't work on enhancements for the V2 player, because all our efforts go into the new V3 player, where your request has already been solved.
As I know you're already switched to the beta version, I'll close this.
