### ISSUE TITLE
PWP nur in Episodes, und nicht in Beiträgen?

### ISSUE THREAD

**Issue by juergv** [podlove/podlove-web-player#246]
Leider zeigt mein ansonsten geniales WP-Theme (Unicorn by Themeforest) die Episodes in der Vorschau auf der Homepage ziemlich unschön an. Im Screenshot in «Recent», während die Beiträge in «Aktuelle Sendungen» schöne Vorschauen zeigen.

In den Beiträgen wird aber der PWP mit dem manuellen Link [podlove-episode-web-player] oder [podlove-web-player] nicht angezeigt.

- Ist es möglich, dass der PWP nur in Episodes erscheint, und nicht in Beiträgen?
- Kann man die Episodes-Vorschau schöner gestalten?
- Oder könnte man den PWP automatisch auch in die Beiträge setzen?

Danke für Euren Support!
![bildschirmfoto 2015-07-03 um 16 45 38](https://cloud.githubusercontent.com/assets/13167439/8501255/124eb6fa-21a4-11e5-8b82-1ba9d6db83a7.png)

**Comment by timpritlove** [comment]
In Beiträgen fehlt der Kontext: welche Episode sollte angezeigt werden? Derzeit haben wir noch keine Möglichkeit, eine Episode explizit zu referenzieren.

Was ist der Use Case hier, dass die Episode in einem Beitrag angezeigt werden sollte statt in der Episode selbst?

**Comment by juergv** [comment]
Hallo Tim,

Danke für die schnelle Rückmeldung!

Mein WP-Theme (Unicorn by Themeforest) zeigt die Episoden in der Vorschau auf der Homepage ziemlich unschön an, siehe http://www.bienenpodcast.info/ unter «Recent».

Und nicht web-affine User suchen lange, bevor sie merken, dass man auf den kleinen Titel (und nicht auf das Bild oder den grauen Hintergrund-Balken) klicken muss, um zur Episode zu gelangen. Da unser Zielpublikum durchschnittlich einiges über 50 Jahre ist, kann man nicht unbedingt voraussetzen, dass die User web-affin sind.

Mir wäre natürlich lieber, ich könnte Episodes nutzen. Sonst macht das Podlove-System ja keinen Sinn ...

**Comment by timpritlove** [comment]
Dreierlei:

* ich habe irgendwie noch nicht ganz verstanden, was genau das Problem ist
* es geht auch nicht um den Web Player sondern um den Podcast Publisher.
* wir reden hier über Umsetzung nicht Bugs, daher ist GitHub nicht der richtige Ort

Daher wäre es mir lieber, wir würden die Diskussion hier weiterführen:

https://sendegate.de/c/podlove

Ich mache das Ticket hier mal zu, vielleicht kannst du das im Sendegate noch mal ausführlich darlegen, was geht und was nicht und da lesen dann auch gleich viel mehr Leute mit. Danke.

**Comment by juergv** [comment]
Werde ich machen. Danke!
