### ISSUE TITLE
Podlove Episoden Webplayer wird nicht angezeigt

### ISSUE THREAD

**Issue by 404Keneth** [podlove/podlove-web-player#247]
Hallo,

ich habe ein kleines Problem und zwar wird bei mir der Podlove Episoden Webplayer nicht angezeigt. 

Zur Info ich habe eine Podcast Show die läuft und da klappt der Webplayer, nun habe ich mit einer neuen Show angefangen und wenn ich den Code [podlove-episode-web-player] einfüge wird aber kein Webplayer angezeit. 

Wahrscheinlich ist es irgendwo ein kleiner Fehler den ich nicht finde. Ich habe im Anhang mal paar Screenshots gemacht wie es im Backend aussieht. 

![screenshot 1](https://cloud.githubusercontent.com/assets/13000543/8533696/232117f8-2437-11e5-99b4-a079908536c1.jpg)
![screenshot 2](https://cloud.githubusercontent.com/assets/13000543/8533698/23269df4-2437-11e5-95c6-3f3338dcf1f6.jpg)
![screenshot 3](https://cloud.githubusercontent.com/assets/13000543/8533697/2324119c-2437-11e5-88df-9f363b05a4e9.jpg)

Auf dem Screenshot 3 kann man sehen, dass ich nur die unteren ausgewählt habe, das habe ich gemacht, da dieser Podcast einen eigenen Feed haben soll. Außerdem ist vielleicht noch erwähnen, dass ich den Podcast Files ein Slug (fua) in den Einstellungen gegeben habe das immer für die Show gleich ist.

Habt ihr eine Idee woran es liegen kann? Ich habe schon viel Probiert, aber leider bis jetzt keine Lösung gefunden.

Vielen Dank!!
Keneth

**Comment by eteubert** [comment]
Kannst du bitte den Abschnitt aus dem "Podlove > Support" Menü posten?

**Comment by 404Keneth** [comment]
Hallo eteubert,

Hier der Screenshot: 

![screebshot 4](https://cloud.githubusercontent.com/assets/13000543/8543318/594c655c-249c-11e5-8d0e-88bd003ba249.jpg)

Danke schon mal für deine Hilfe!

**Comment by eteubert** [comment]
Deine Assets sind doppelt, das musst du beheben.
Ggf. musst du anschließend die Assets zuweisen, in `Podlove > Expert Settings > Web Player`

**Comment by 404Keneth** [comment]
Hallo Eteubert,

jetzt weiß ich was du meinst. Auf die Lösung bin ich noch nicht gekommen. 

Eigentlich habe ich zweimal Mp3, M4A usw. eingegeben und auch zweimal eigene Feeds für die verschiedenen Shows gemacht, damit ich dann auch später zwei verschiedene Feeds für iTunes und co. habe. Wenn ich jetzt die Assets ändere, wird wahrscheinlich die alte Podcast Show nicht mehr funktionieren.

Hättest du dafür eine Lösung? Oder gibt es hier auf GitHub / im PodLove Wiki irgendwo eine einfach Anleitung wie man zwei verschiedene Show (mit zwei Feeds) auf einer Wordpress Seite laufen lassen kann?

**Comment by eteubert** [comment]
Ah, verstehe. Nein, das funktioniert so nicht. Du kannst mit Kategorie-Feeds arbeiten, aber mehrere komplett unabhängige Shows in einem WordPress sind nicht vorgesehen. Das geht nur mit einem Netzwerk, siehe http://docs.podlove.org/guides/podcast-network/.
