### ISSUE TITLE
Chrome osx - Hohe CPU Auslastung wenn im Vordergrund

### ISSUE THREAD

**Issue by medoni** [podlove/podlove-web-player#250]
Sobald der Tab mit dem Player im Vordergrund ist, hat der Chrome-Tab 44% Auslastung bei Wiedergabe (Chrome Taskmanager). Im Hintergrund hingegen nur 4%

In der Aktivitätsanzeige im Vordergrund 65% Auslastung, Hintergrund <10%.

Getestet: http://minkorrekt.de/minkorrekt-folge-57-personal-istkosten

**Comment by plutonik-a** [comment]
Kann ich persönlich auf meinem System nicht bestätigen. Welches System + Browserversion + Gerät sorgt denn da für die Probleme? Und vor allem: Besteht das Problem nach einem Neustart immer noch? ;)

**Comment by medoni** [comment]
OSX 10.10.5
Chrome 45.0.2454.85 (64-bit)
MacBook Pro (Retina, 13-inch, Late 2012)

Ja besteht auch nach Reboot noch. Besteht auch bei einem neuangelegten Benutzer ohne jegliche Erweiterungen.

**Comment by medoni** [comment]
Möglicherweise liegts an `span.mejs-time-buffering`. Gebe ich diesem einen `display:none` ist die Auslastung akzeptabel bei 7-8% (Chrome Taskmanager)

Grund scheint `animation: buffering-stripes 2s linear infinite` zu sein.

**Comment by plutonik-a** [comment]
Klingt aber auch eigenartig. Die Bufferanzeige ist ja nicht permanent aktiv. Dann müsste das Problem ja nach Beenden des Bufferns verschwunden sein und dein Rechner sich beruhigen. Merkwürdig.

**Comment by line-o** [comment]
Kann ich hier nachvollziehen. Wird in der kommenden Version kein Problem sein, da wir da die Progressbar selbst implementieren und nicht die der Mediaelement.js Bibliothek verwenden.
