### ISSUE TITLE
V3: Quick question about embedding

### ISSUE THREAD

**Issue by dankebitte** [podlove/podlove-web-player#252]
Hi,

quick question: How can I embed Podlove publisher episodes on an external website?

Cheers

**Comment by line-o** [comment]
As soon as we expose the UI with the correct iframe/HTML-code :)

**Comment by plutonik-a** [comment]
Thanks for your request! As @line-o mentioned above, we are working on it.
Related to ticket: https://trello.com/c/1slUciaC
and already reported in this ticket: https://trello.com/c/yDdzf9cL
