### ISSUE TITLE
V3: Use SVG-Icons

### ISSUE THREAD

**Issue by Schweinepriester** [podlove/podlove-web-player#255]
... as http://mediaelementjs.com/ does.

Links:
- http://caniuse.com/#feat=svg
- https://css-tricks.com/icon-fonts-vs-svg/

**Comment by plutonik-a** [comment]
Thanks, this request already is on our todo list.

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/ahnuqTyP
