### ISSUE TITLE
Share listening progress from web player with podcast apps

### ISSUE THREAD

**Issue by tuxbox** [podlove/podlove-web-player#262]
Hi,
based on [this issue](https://github.com/podlove/podlove-subscribe-button/issues/77) I would like to ask for a "sync" button in the webplayer that starts my favorite podcast app and shares my progress.
This should be possible with the new intent scheme at least on Android and of course some app support.
The scenario in which this comes handy is the following.
I start listening to the podcast at work using the web player, when I leave I want to continue on my mobile using my fav app during my commute.
The Chrome tabs get synced so I have the right position at hand in the browser, but I need to manually open my app, select the podcast, then the episode and then seek to the right position (best case scenario :-) ).
This could be solved by a simple link that looks like this:

```
intent://freakshow.fm/#Intent;scheme=playback;S.episode=<some-identifier-tbd>;S.position=4711000;end;
```

The expected behavior would be that the podcast app handles the intent, opens the right episode and seeks to the 1:18:52 mark (outside of the webplayer scope but to give the whole picture).
In the traditional scheme this probably would have looked like this

```
playback://freakshow.fm/episode/<some-identifier>/position/4711000
```

The advantage of the "new" intent scheme is that there's no more need for parsing on the receivers side, as the S.\* params will be delivered correctly as params by the OS.

**Comment by plutonik-a** [comment]
Thanks for your request! Iit would be a very nice feature and hopefully be solved in one of our fututre releases.
I made a ticket for it: https://trello.com/c/uGegFbBw
