### ISSUE TITLE
hide scrubber until playback starts

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-web-player#267]
As noticed by https://twitter.com/ostsender/status/665235898599120897, the scrubber appears like a graphics glitch, indenting the play bar. Maybe a simple fix would be to hide it, until the user starts the playback.

**Comment by plutonik-a** [comment]
Opened Ticket https://trello.com/c/84E10PjD

**Comment by plutonik-a** [comment]
We slightly changed the layout of the progressbar and gave it a bit more space, so the scrubber is still visible while the player is inactive, but can be reached easily.
Was fixed in our current release https://github.com/podlove/podlove-web-player/releases/tag/v3.0.0-rc.5
