### ISSUE TITLE
Customize tint color

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#268]
The new player uses a greenish color for some element. However that does not match the theme of my podcast very nice. I would like to change that in settings.

**Comment by plutonik-a** [comment]
We are currently releasing a documentation of v3.0 where choosing a theme or customized theming is explained.
If you can't wait for that, here's a brief explanation how to choose a theme:

The CSS files are available both in minified or extended version
For example:
`pwp-dark.css`
`pwp-dark.min.css`

### Pick one of the color presets
CSS theme files can be found here:
`dist/css/pwp-<name-of-theme>.css`
Previews of available themes can currently be found here:
http://sourcerer.org/examples/themes/

List of available CSS ftheme filenames:
```
pwp-blue-orange.min.css
pwp-creamy.min.css
pwp-dark-blaze.min.css
pwp-dark-gray.min.css
pwp-dark-green.min.css
pwp-dark.min.css
pwp-jungle-green.min.css
pwp-light-gray.min.css
pwp-light.min.css
pwp-midnightblue.min.css
pwp-silver-blaze.min.css
pwp-silver.min.css
```
`Place the relevant CSS file in the head of your document.


### Create Your Own Theme
Path to theme folder:
  `/src/sass/themes/`
Open any `scss` file and modify an existing theme by playing with colors and changing their values:<br>
For example `_light.scss`

```
//
// Light Theme
// --------------------------------------------------

$theme: (
    player-base:     #fff,
    player-contrast: #000,
    meta-base:       #fff,
    meta-contrast:   #535353,
    accent-base:     #42478a,
    accent-contrast: #fff
);
```

After modifying colors, check resulting color contrasts, they might not fully meet accessibility standards.
If you know what you're doing, you could also modify the color functions.

Open and edit file:
`/src/sass/_colors.scss`

**Comment by funkenstrahlen** [comment]
Nice! That is exactly what I am looking for :smiley: I will wait for the official documentation to be released.

**Comment by plutonik-a** [comment]
Reopened:
Use this as a temporary theming guide. The full doc will follow soon.

**Comment by plutonik-a** [comment]
http://docs.podlove.org/podlove-web-player/
