### ISSUE TITLE
download format selection dropdown is hard to discover

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#269]
It is very hard to tell that this is actually a dropdown to select a format. Maybe add a downward arrow add the end?

![screen shot 2015-11-14 at 14 50 00](https://cloud.githubusercontent.com/assets/144173/11163858/04e841d0-8adf-11e5-8f08-fe99250eb7f9.png)

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/glonp7Az

**Comment by plutonik-a** [comment]
Fixed: https://github.com/podlove/podlove-web-player/commit/e24af7eb2077b6990dde84b21e532ce452a0842d
