### ISSUE TITLE
Hide licence area if licence is unclear

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#270]
If there is no explicit licence defined in Podlove, the player should hide the licence area.

![screen shot 2015-11-14 at 14 51 45](https://cloud.githubusercontent.com/assets/144173/11163867/6b46f8ea-8adf-11e5-86b4-248c39c8425d.png)

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/rhGCcqwA

**Comment by plutonik-a** [comment]
This feature is fixed in our current release https://github.com/podlove/podlove-web-player/releases/tag/v3.0.0-rc.5
