### ISSUE TITLE
Subtitle in Info Area needs more line spacing

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#271]
I think the subtitle in the info area needs more line spacing. It looks a little weird:

![screen shot 2015-11-14 at 14 53 52](https://cloud.githubusercontent.com/assets/144173/11163871/9d9e7408-8adf-11e5-82f0-7f37dec9ec1f.png)

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/P5RPvqrP

**Comment by plutonik-a** [comment]
Fixed with https://github.com/podlove/podlove-web-player/commit/018ee8de3510b31e12f6d02059791414106fafe1
This fix will be in the upcoming release.
