### ISSUE TITLE
V3: Feedback / Contact area in the player

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#274]
If the player will be embeddable there should be a clear way to give feedback to the podcaster. There is already a link to the podcast episode page, but I think it there should be a more explicit "Feedback, this way" thing.

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/ffuCyHQ1

**Comment by plutonik-a** [comment]
This is an often requested feature and will be considered in one of the future versions.
