### ISSUE TITLE
Bug: Clicking on title or podcastname header opens URL inside the iframe

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#275]
Clicking on the title or the podcastname opens the URL inside the iframe of the player, so the player disappears.

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/nhFCFcmw

**Comment by line-o** [comment]
Fixed with https://github.com/line-o/podlove-web-player/commit/68d585c13622f092f511bc42e3f945f410ef21ac
