### ISSUE TITLE
View in iOS (iPhone)

### ISSUE THREAD

**Issue by nitramred** [podlove/podlove-web-player#276]
I've installed the experimental player in Podlove and had a look at it unser iOS – the player is larger than the content column.
![img_6821](https://cloud.githubusercontent.com/assets/4311852/11164058/d7e19f04-8ae5-11e5-9f2b-0a9e2a88a608.jpg)
Maybe there's a way to make this look nicer :-)

**Comment by plutonik-a** [comment]
Thanks, we experienced that bug already. It appears only in mobile Safari and should be fixed soon.

**Comment by eteubert** [comment]
I (think I) fixed it in the Publisher here: https://github.com/podlove/podlove-publisher/commit/aa5a1f189c37765129fd261762766b87e14adc32
But if you have an independent solution, that'd be even better.

**Comment by nitramred** [comment]
OK, sounds great! Thanks for the quick reply!

**Comment by funkenstrahlen** [comment]
I also see this kind of bug. @ericteubert Do you know when you can release this fix?

**Comment by eteubert** [comment]
It should be fixed in the current version (2.3.4)

**Comment by funkenstrahlen** [comment]
Works! Thanks for the quick fix!

**Comment by line-o** [comment]
Fixed with https://github.com/line-o/podlove-web-player/commit/ea9470e7b226c71dd6b751a8bc0edba215e616ae
