### ISSUE TITLE
Transport button

### ISSUE THREAD

**Issue by nitramred** [podlove/podlove-web-player#277]
A small design issue: The transport button right now has three different sizes depending on the mouse hovering over it. And it is hardly recognizable and "grabable" at its starting position.
![button_1](https://cloud.githubusercontent.com/assets/4311852/11164108/bfe65b22-8ae7-11e5-8741-848f0a819541.png)
![button_2](https://cloud.githubusercontent.com/assets/4311852/11164109/c345b6b4-8ae7-11e5-8941-f8a5795b188f.png)
![button_3](https://cloud.githubusercontent.com/assets/4311852/11164110/c5c55052-8ae7-11e5-9cce-84c9b7fa9de3.png)

**Comment by plutonik-a** [comment]
Thanks, was already reported by @katrinleinweber https://github.com/podlove/podlove-web-player/issues/267

**Comment by nitramred** [comment]
Oh, OK. I've read the issue title but had another idea of what's behind it :-)

**Comment by plutonik-a** [comment]
Opened Ticket https://trello.com/c/84E10PjD
