### ISSUE TITLE
(too) much whitespace under v3 player

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-web-player#279]
When I use the template section

```
{{ episode.player }}
<div style="float:right">
    {{ flattr.button({ style: 'large' }) }}
</div>
{{ episode.summary }}
```
there are about 2 text lines of white space under the player before the summary is rendered:
![screen shot 2015-11-15 at 14 51 12](https://cloud.githubusercontent.com/assets/9948149/11169025/5a0336e2-8ba8-11e5-835c-85551e35049a.png)

`{{ episode.player }}{{ episode.summary }}` isn't as nice in the template code, but reduces the space to ca. 1 line:
![screen shot 2015-11-15 at 14 51 44](https://cloud.githubusercontent.com/assets/9948149/11169027/6af8f496-8ba8-11e5-8098-973127034c79.png)

Is there anything in the player itself, that forces the empty space and is it intended to be ca 50% more then below the v2 player?

**Comment by line-o** [comment]
No, that whitespace is outside of the iframe/ the iframe itself.
Specifically, the rule for `.entry-content iframe` adds a bottom margin on your site.

**Comment by katrinleinweber** [comment]
Hm, OK, thanks! Wherever that rule is defined, it didn't affect the v2 player.

**Comment by line-o** [comment]
Sure, the v2 player was not in an iframe.
