### ISSUE TITLE
V3: "Show URL"-Funktion integrieren

### ISSUE THREAD

**Issue by LarsNaber** [podlove/podlove-web-player#280]
Wenn man in den neuen Player die Funktion zur Anzeige der Feed-URL integrieren würden, bräuchte man diese Funktion nicht mehr über das Template bereitstellen und dort separat gestalten.

**Comment by funkenstrahlen** [comment]
linked to #273

**Comment by line-o** [comment]
Wir planen den Subscribe-Button zu integrieren. Löst das dein Problem?

**Comment by line-o** [comment]
@funkenstrahlen was hat das mit den Kontributoren zu tun? Das man diese auch "extra" stylen muss?

**Comment by LarsNaber** [comment]
@line-o Meiner Ansicht löst das mein Problem leider nicht. Ich möchte gerne die unterschiedlichen Audioformate für eine einzelne Episode zum Download anbieten. Dafür gibt es die Möglichkeit, im Template etwas zu machen: Auswahlliste mit Formaten und 2 Buttons "Download" und "Show URL".

Beispiel:
http://aufdistanz.de/auf-distanz-0000-nullnummer/

Der Player V3 zeigt in der Download-Funktion die Auswahlliste der Audioformate, kann aber nicht die URL anzeigen. Diese kleine Funktion fehlt mir da. Wenn das da wäre, könnte man die Funktion aus dem Template komplett entfernen, die im Beispiel oben noch unter dem Player sichtbar ist. Mir fehlt also nur der Button "Show URL".

Der Subscribe-Button liefert die Adresse für den RSS-Feed mit den Episoden und behandelt nicht eine einzelne Episode. Deswegen passt das m.E. nicht so gut. Aber wenn ich das hier eben mit erwähnen darf: Es wäre schön, wenn ich auch in der zukünftigen Funktion für die Subscribe-Funktion den Feed für das gewünschte Audioformat wählen könnte, was derzeit nicht möglich ist.

Besten Dank für Eure Mühe.

**Comment by plutonik-a** [comment]
Ticket https://trello.com/c/tSBew6Ud

**Comment by line-o** [comment]
fixed in 3.0.0-rc2
