### ISSUE TITLE
V3: Download opens new tab

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-web-player#281]
Hi,

when I click download in the download section of the new player a new browser tab is opened. After the download started the new tab closes automatically (Chrome, Firefox). In Safari the browser stays open. The stand-alone download buttons don't open a new browser tab and the download starts immediatly. 

Website: http://technische-aufklaerung.de

**Comment by plutonik-a** [comment]
Ticket https://trello.com/c/Dk92mkoN

**Comment by line-o** [comment]
fixed with 4c5ef06

**Comment by plutonik-a** [comment]
This fix will be in the upcoming release.
