### ISSUE TITLE
Generalise Chapters Visibility option

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-web-player#282]
There is currently a `Chapters Visibility` option in the Publisher's `Expert Options`. Since there is now also an `Info` tab, could that option please be turned into an `Expand Player Tab` with `None`, `Chapters`, `Info`, etc. The latter in particular could simplify the templating of an episode website :-)

**Comment by funkenstrahlen** [comment]
This should be a feature request in the podlove publisher project.

**Comment by katrinleinweber** [comment]
[Moved](https://community.podlove.org/t/generalise-chapters-visibility-option/443). Wasn't sure who the "owner" of the Web Player settings in the Publisher was.
