### ISSUE TITLE
V3: Scrollbars unter Windows

### ISSUE THREAD

**Issue by shiller79** [podlove/podlove-web-player#285]
geöffneten Erweiterungen (Kappitelliste, Teilen, Downloads oder Infos) erscheint am rechten Rand eine haber Scrolbar. Nur im unteren Teil, unabhängig ob es was zu scrollen gibt oder nicht.
Windwos 7 und Windows 10 unter Edge, IE, Firefox und Chrome

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/FiSorqCq

**Comment by fairsein** [comment]
Siehe auch hier: https://sendegate.de/t/podlove-webplayer-3-podcast-logo/2769
