### ISSUE TITLE
V3: Option für Kapitel standardmäßig ausklappen wird ignoriert

### ISSUE THREAD

**Issue by saerdnaer** [podlove/podlove-web-player#286]
Wir hatten bei RadioOSM im Wordpress den Player2 so eingestellt, dass die Kapitel standardmäßig ausgeklappt sind. Wenn ich den Player3 aktiviere wird diese Einstellung ignoriert und der Nutzer muss die Kapitel erst selbst ausklappen.

**Comment by katrinleinweber** [comment]
Flucht nach vorne: https://community.podlove.org/t/generalise-chapters-visibility-option/443

**Comment by line-o** [comment]
Ja, die Konfiguration hat sich geändert. `initialTab` gibt nun an welcher Tab initial geöffnet werden soll.
In deinem Fall wäre das also

    {
        ...
        "initialActiveTab": "Chapters",
        ...
    }

**Comment by katrinleinweber** [comment]
Wo kann das eingestellt werden? In der UI habe ich nix gefunden, aber ich traue mich an'ne Konfigurationsdatei schon ran ;-)

Wie wäre es mit einer automatische Migration, sodass beim Upgrade des PPP, oder beim Einschalten des PWP3 die obige config automatisch gesetzt wird, wenn zuvor `Chapter Visibility` = `Visible…` war?

**Comment by plutonik-a** [comment]
Ich muss Juris Kommentar oben noch korrigieren:

Die notwendige Einstellung für den initial aufgeklappten Tab ist mit `"activeTab": "Kapitel"` zu benennen.
Du setzt denParameter mit den übrigen Playerparametern in deiner `index.html` innerhalb eines `<script>` Tags - wo auch z.B. die Kapitelmarken stehen.
Im Moment habe wir es so gelöst, dass du einfach die jeweilige Tab-Überschrift setzen musst, um den Tab zum Start geöffnet zu haben.

**Comment by line-o** [comment]
Die Tab-Headline kann als Identifikator natürlich nicht bleiben. Jeder Tab erhält jetzt zusätzlich noch eine ID über die er dann angesteuert werden kann. https://trello.com/c/3x0l0Bua/190-jedem-tab-eine-tab-id-zuweisen-und-diese-fur-activetab-verwenden

**Comment by line-o** [comment]
fixed with 1055509

**Comment by katrinleinweber** [comment]
Es funktioniert leider [noch](https://github.com/podlove/podlove-publisher/releases/tag/2.3.5) nicht. Habe es mit Cache-Leeren, Podlove-Reparieren und die Option Hin-und-Her-Schalten probiert. Zum Template muss man nichts hinzufügen, oder?

![screen shot 2015-12-05 at 15 27 29](https://cloud.githubusercontent.com/assets/9948149/11608280/073c5d18-9b65-11e5-8670-41ed3fd05f73.png)

**Comment by eteubert** [comment]
Das ist in erster Linie ein Publisher-Bug. Das Setting wirkt noch nur auf Player V2.
