### ISSUE TITLE
Lautstärke-Symbol wird unter Chrome (Mac OS X) nicht angezeigt

### ISSUE THREAD

**Issue by Xjs** [podlove/podlove-web-player#287]
![screen shot 2015-11-18 at 15 03 41](https://cloud.githubusercontent.com/assets/58270/11242978/948421aa-8e05-11e5-894e-0ab142db656d.png)

Das Lautstärke-Symbol wird unter Chrome (Mac OS X) nicht angezeigt. Vgl. http://infracast.de/

**Comment by plutonik-a** [comment]
Wenn du in der Datei 

```
http://infracast.de/wp-content/plugins/podlove-podcasting-plugin-for-wordpress/lib/modules/podlove_web_player/player_v2/player/podlove-web-player/static/podlove-web-player.css?ver=2.0.19
```

aus dem entsprechenden Volume Button 

```
.podlovewebplayer_wrapper .mejs-button.mejs-volume-button button {
```
die Klasse `button` löschst, wird die Datei `controls.svg` als Hintergrundbild angezeigt.

Übrigens ist da noch mehr im Layout eigenartig:
Da ist ein großer Abstand von Überschrift zum Player, in dem ein schwarzer Balken sichtbar wird.
Dann sitzt der Pfeil im Playbutton nicht richtig.
Beim Drüberfahren über "Read More" ist der untere Rand zu kurz gesetzt, weil er vom Theme eine feste und zu kurze Breite bekommt.

Vielleicht kommt es insgesamt wegen dem Theme zu Layout-Kollisionen?
Gab es da deinerseits Änderungen oder Updates?
Wenn du magst, probiere doch testweise mal den v3-beta Player aus, da die Styles unabhängig vom WP Theme funktionieren.

**Comment by Xjs** [comment]
Der schwarze Balken unter der Überschrift und der untere Rand von »read more« sind im Theme so beabsichtigt, vgl. https://www.competethemes.com/tracks-live-demo/.

v3 sieht gut aus, danke für den Tipp!
