### ISSUE TITLE
"Get URL for this" encoding gives a broken link

### ISSUE THREAD

**Issue by srenatus** [podlove/podlove-web-player#290]
Hi there.

Clicking on "Get URL for this" for example [here](http://logbuch-netzpolitik.de/lnp156-bereitbandausbau) gives `http://logbuch-netzpolitik.de/lnp156-bereitbandausbau%23t%3D00:00` which, if copied to a new tab, gets me a [404](http://logbuch-netzpolitik.de/lnp156-bereitbandausbau%23t%3D00:00). The link `http://logbuch-netzpolitik.de/lnp156-bereitbandausbau#t=00:00` however, [works](http://logbuch-netzpolitik.de/lnp156-bereitbandausbau#t=00:00) as it should.

Couldn't find the code in question, so I'll just drop this issue here, hoping it's still relevant.

Thanks!
Stephan

**Comment by line-o** [comment]
Thanks for your report @srenatus
Even if not obvious it is in fact a duplicate of https://github.com/podlove/podlove-web-player/issues/245

http://logbuch-netzpolitik.de seems to have installed both Podlove-Publisher and Podlove-Web-Player (WP). /cc Can you confirm that @timpritlove?

**Comment by srenatus** [comment]
@line-o Oh, right. Thanks! I'll close this.
