### ISSUE TITLE
Web Player V3 shows scroll bars where it shouldn't

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-web-player#291]
Hi,

I use the latest version of the Podlove Publisher (2.3.4) and enabled the Web Player V3. There is one episode on my [site](http://technische-aufklaerung.de/) which shows scroll bars at the bottom and the right side of the web player (either on the front page and on the specific [episode page](http://technische-aufklaerung.de/ta018-oeffentliche-sitzung-am-05-11-2015/)). I use the same template for adding the player and contributors on every episode. I also clicked the magic repair button at Pdolove --> Support --> Attempt Repair and cleared the cache.

![bildschirmfoto 2015-11-21 um 18 12 47 1](https://cloud.githubusercontent.com/assets/9519201/11319642/03f1db34-907e-11e5-8f5c-00b82517fe3b.png)

**Comment by plutonik-a** [comment]
The problem is caused by the long, not-breaking headline.

https://trello.com/c/pwun5ANb

I fixed it with https://github.com/podlove/podlove-web-player/commit/eedd8909313684977a8cd0c0c16b78f1e1373d25

The bugfix is on the next player release soon to come.

**Comment by jonasschoen** [comment]
Perfect. Thank you :-)
