### ISSUE TITLE
V3: Web Player misses volume slider

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-web-player#292]
I just realised that the new player is missing a volume slide. I can imagine that people (e. g. my mother) don't know how to change the system's volume and that they would want that feature. Maybe you already discussed this or have it on your roadmap, but I didn't find it in your Trello board.

**Comment by plutonik-a** [comment]
Opened ticket https://trello.com/c/cVxQykCx

**Comment by Kambfhase** [comment]
I think this is intentional. I don't know your mother, but most ppl. do know how to change their computers volume. For those, having an extra slider + icon is just visual noise.

**Comment by jonasschoen** [comment]
Hmm, I think there are several people who are used to change the volume at the player and not the general system volume. YouTube, SoundCloud and almost every video player app offer their own volume slider. 
Furthermore you may want to adjust the podcast's volume in relation to another audio source.

**Comment by funkenstrahlen** [comment]
Maybe this should be a desktop only feature then?

**Comment by Kambfhase** [comment]
> YouTube, SoundCloud and almost every video player app offer their own volume slider. 

Just because everyone does it, that doesn't mean its a good idea.

> Furthermore you may want to adjust the podcast's volume in relation to another audio source.

That's a job your operating system should be able to do. If it can't, get yourself a better OS.

> Maybe this should be a desktop only feature then?

As the borders between product classes are disappearing defining „desktop“ has become hard. E.g Should Microsoft's Surface be seen as a desktop? Only when it has a keyboard attached? What about the iPad Pro?

**Comment by line-o** [comment]
At first, @Kambfhase, yes, the volume slider was intentionally left out.

Second, @jonasschoen, we also think there might be several use cases were having a volume slider might be a good thing to have.
These use cases usually are rare especially for podcasts and therefore will likely be part of a new settings menu. That means changing the volume would require an extra click - a feature for experienced users.

**Comment by henningkrause** [comment]
+1 for a volume slider within the player!

**Comment by H4kor** [comment]
Really missing the slider. Especially useful when having several applications running (game + podcast).
Additionally it helps to set the volume to a comfortable level without changing the system volume every time. Different application have different base volumes.
