### ISSUE TITLE
V3: Scroll bars at the end of playback

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-web-player#295]
As soon as you are about to hit the end of a podcast episode (when the white "progress knob" hits the right frame), scroll bars will appear. 
![v3 scroll bars](https://cloud.githubusercontent.com/assets/11300164/11716021/1d35f29c-9f47-11e5-9deb-a79eb2b46643.jpg)
Can be seen live at: http://gametalk.fm

I am using:
Plug-in version 2.3.6
Windows 7 64bit
Google Chrome 47.0.2526.73 m (64-bit)
Wordpress 4.3.1

**Comment by Inrumpo** [comment]
I have now updated a few parts of my system. The problem still appears. I am now using:

Plug-in version 2.3.8
Windows 10 64bit
Google Chrome 48.0.2564.109 m (64-bit)
Wordpress 4.4.2

**Comment by fairsein** [comment]
Hi Joey,

I create a trello card for it: https://trello.com/c/qAuohJtf/213-scroll-bars-am-ende-der-folge-sichbar

Best fairsein
