### ISSUE TITLE
Import works only partially

### ISSUE THREAD

**Issue by iSchack** [podlove/podlove-web-player#296]
Today I moved two podcasts with podlove from server A to server B. Both podcasts were on the latest versions of both, Wordpress and Podlove Publisher when I downloaded the export files yesterday.

With the first podcast everything went as expected.

With the second one, the import only seems to have worked partially. Here's what I did:
1. Set up Wordpress
2. Install Podlove (fresh from plugin repository)
3. Import Wordpress data
4. Import Podlove data

As for the first podcast, I was presented a page after the import, telling me that everything worked fine. With the second podcast, the import started and then went to a blank page.

The result can be seen at schackschnackt.de, where episode 2 was imported correctly but episode 1 and 3 through 8 weren't.

I assumed I did something wrong and went through the routine described above for three times now, always with the same result.

Any ideas why this might be happening and how to fix it?

Thanks,
Sebastian

**Comment by timpritlove** [comment]
You have posted this under "Web Player" which is unrelated to your issue. Also, we are only handling bug fixes on GitHub, so please submit your request on <https://community.podlove.org/c/podlove-publisher>. Thanks.
