### ISSUE TITLE
V3: How to include the player into static html

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#299]
I want to build a site and add the player manually.

How can I do that? Any examples?

**Comment by line-o** [comment]
You should definitely look into the [webplayer docs](http://docs.podlove.org/podlove-web-player/) which is aimed at people that want to integrate the player in their site or system.
The [gettting started](http://docs.podlove.org/podlove-web-player/guides/getting-started.html) page, provides a brief overview on how to achieve your goal.
Some settings are covered in greater detail and we will add more of those along the way. 
If you find any problems or inconsistencies, we would be happy to hear that.
And if you have further questions we will gladly answer them.
