### ISSUE TITLE
Falscher Player in "letzte Beiträge" PWP v3

### ISSUE THREAD

**Issue by kampfq** [podlove/podlove-web-player#301]
Mit Startseite: "deine letzten Beiträge" und aktivierten Webplayer v3 wird auf der Startseite noch Player Version 2 geladen, was den HTML 5 fallback zur Folge hat :(
![screen shot 2016-01-11 at 14 21 55](https://cloud.githubusercontent.com/assets/7052906/12234641/c3513b56-b86e-11e5-8bfa-f45280ff5048.png)

**Comment by Kambfhase** [comment]
Klingt für mich eher nach einem Fehler im Publisher.

**Comment by kampfq** [comment]
kk, hier schließen und im publisher ticket aufmachen? oder lesen publisher-entwickler hier mit? :)

**Comment by plutonik-a** [comment]
Hi Ben, du kannst das Ticket ruhig offen lassen, der Publisher-Techniker ist informiert ;)

**Comment by eteubert** [comment]
1. Hast du das Web Player Plugin installiert? Wenn ja, bitte deaktivieren.
2. Hast du ein Caching Plugin aktiv? Wenn ja, bitte Cache leeren.

Hilft das?

**Comment by kampfq** [comment]
War es ein Cacheproblem. Thx :)
