### ISSUE TITLE
Download Button does not work in Safari

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#303]
When I press the Download Button in Safari, it does not work. Same for iOS and MacOS.

It works fine in Chrome though.

Live Website with the problem: http://podcast.funkenstrahlen.de/2016/01/16/fs084-grundrechte-gelten-nicht-im-weltraum/

**Comment by funkenstrahlen** [comment]
Seems to work now after upgrading to the new Safari Version 9.0.3. Anyone still having an older version to test?

**Comment by plutonik-a** [comment]
Download works perfectly fine on Safari 9.0.2 / OS X 10.10.5.

**Comment by funkenstrahlen** [comment]
Ok, close this for now.

I will report if I can reproduce it.
