### ISSUE TITLE
V3: Selecting download URL is nearly impossible mobile devices

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-web-player#304]
When I try to select the direct link download URL of an episode on a smartphone (iOS) I am not able to do it. The selection focus always resets itself. This might be caused by some other elements around the URL.

Idea: Select the whole URL automatically when the user clicks/presses inside the URL string.

**Comment by plutonik-a** [comment]
Thanks for your idea!
That's an important feature that we obviously missed to implement so far.

I created a ticket for it: 
https://trello.com/c/BhQtjocC
