### ISSUE TITLE
Uncaught SecurityError

### ISSUE THREAD

**Issue by erdebene** [podlove/podlove-web-player#306]
Mein Wordpress wirft die nachfolgende Meldung aus:
![image](https://cloud.githubusercontent.com/assets/11456963/12677176/5d10c712-c697-11e5-89c8-a245f9bbd8d4.png)
Kann ich zur Beseitigung etwas unternehmen?

**Comment by eteubert** [comment]
Das iframe muss auf der exakt gleichen Domain eingebunden werden wie die, die es generiert. Das kann sonst nur serverseitig behoben werden, Stichwort "CORS". Ist aber sehr technisch.

Hilfe z.B.

- http://enable-cors.org/server_apache.html
- http://enable-cors.org/server_php.html
