### ISSUE TITLE
Outdated documentation for chaptersVisible

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-web-player#310]
The documentation still mentions "chaptersVisible" setting which does not exist any more: http://docs.podlove.org/podlove-web-player/appendix/json-config.html

It should mention the "activeTab" setting instead and list the possible options.

**Comment by plutonik-a** [comment]
Thanks, I'll fix that.

**Comment by plutonik-a** [comment]
Fixed with https://github.com/podlove/podlove.github.com/commit/63019eab1b9acebf995e178509c16e0407751f36
