### ISSUE TITLE
V3 (rc.5): OS X Scrollbars when mouse is attached

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-web-player#312]
- OS X
- Chrome
- Only when an external mouse is attached
- Only at certain breakpoints (looks like `screen and (min-width: 77.5em)`)

<img width="675" alt="screen shot 2016-02-26 at 17 31 00" src="https://cloud.githubusercontent.com/assets/235918/13348863/f73d46a6-dcb0-11e5-96cb-f443a17f6c3b.png">

**Comment by fairsein** [comment]
Can be then same like this: https://github.com/podlove/podlove-web-player/issues/285
Trello Card for this will then be this: https://trello.com/c/FiSorqCq/188-tabsize-issues-unter-windows-und-linux-fixen
