### ISSUE TITLE
New webspace, Chapter file doesn't load

### ISSUE THREAD

**Issue by timokracke** [podlove/podlove-web-player#315]
Hi all,

I had to move my website to a new provider.
After moving the whole website, everything was fine again.

Example site:
http://www.dergenealoge.de/podcast-35-familienforschung-in-daenemark/

The only thing is that the chapter file isn't loading any more. The file is available at the correct directory and the rest of the setup works well. The next thing is that the player doesn't shows the total duration of a episode. After you hit play, the time is calculated correct.

The code I used is this
`[podloveaudio src="http://www.dergenealoge.de/podcast/dg035_201602.mp3" title="Podcast #35 Familienforschung in Dänemark" chaptersVisible="true" chapters="http://www.dergenealoge.de/podcast/dg035_201602chapters.txt" poster="http://www.dergenealoge.de/podcast/dg_logo.jpg"]`

Chapter file is this:
[http://www.dergenealoge.de/podcast/dg035_201602chapters.txt](http://www.dergenealoge.de/podcast/dg035_201602chapters.txt)

Error log files doesn't shows up any errors regarding the chapter-file.

I'am not sure what is wrong or where to look.
Thanks for your support.

**Comment by plutonik-a** [comment]
Hi Timo,

##### Duration
According to the [V2 documentation](http://docs.podlove.org/podlove-web-player/versions/v2.html#duration), you need to set the duration in your code like this `[podloveaudio duration="00:58:42"]` to be displayed before the the audio file is loaded.

##### Chapters

The chapters parameter is definitely not set here, neither is the file `http://www.dergenealoge.de/podcast/dg035_201602chapters.txt` requested or loaded anywhere.

This is the code I'm looking at:
```
<script >
var pwp_settings_1 = {
    "pluginPath": "http:\/\/www.derGenealoge.de\/wp-content\/plugins\/podlove-web-player\/static\/",
    "alwaysShowHours": true,
    "alwaysShowControls": true,
    "chaptersVisible": true,
    "timecontrolsVisible": false,
    "summaryVisible": false,
    "hidetimebutton": false,
    "hidedownloadbutton": false,
    "hidesharebutton": false,
    "sharewholeepisode": false,
    "loop": false,
    "chapterHeight": "300",
    "chapterlinks": "all",
    "poster": "http:\/\/www.dergenealoge.de\/podcast\/dg_logo.jpg",
    "title": "Podcast #35 Familienforschung in D\u00e4nemark",
    "permalink": "http:\/\/www.derGenealoge.de\/podcast-35-familienforschung-in-daenemark\/",
    "duration": "false",
    "audioWidth": "480",
    "audioHeight": "30",
    "features": ["current", "progress", "duration", "tracks", "fullscreen", "volume"]
};
window.setTimeout(function () {
    jQuery('#podlovewebplayer_1').podlovewebplayer(pwp_settings_1);
}, 200);
</script>
```
Maybe you can edit this code manually and add the chapters like this:
```
    "chapters": [{
        "start": "00:00:00.000", 
        "title": "Der Genealoge", 
        "href": "", 
        "image": ""
    }, {
        "start": "00:00:12.000",
        "title": "Herzlich willkommen zum 35. Podcast",
        "href": "",
        "image": ""
    }]
```

**Comment by timokracke** [comment]
Thank you Alexandra!
The curious thing is that it worked on another webspace and Simon Waldherr runs it on an fresh installed wordpress & plwp-plugin - which also worked.

It seems that there is any option that avoids my website to load this text. As I have to update several podcast episodes with your method I would like to have in running in the same way as it was on the old webspace :(

**Comment by fairsein** [comment]
Hi Timo,

For me it sound like a problem with the rights of the file. What rights has the file at the moment?

Best Jan

**Comment by timokracke** [comment]
Hi Jan,


the file itself has 755, which is more then on the old server!

regards Timo

**Comment by timokracke** [comment]
Hi all,


the issue is solved.
My sever was configured that:

php_allow_url_include was off

after turning it on, my chapters are back :)
Thanks for your help - Timo!
