### ISSUE TITLE
Webplayer spams History

### ISSUE THREAD

**Issue by H4kor** [podlove/podlove-web-player#316]
The webplayer creates a new history entry whenever the timestamp is updated.
Occurs in Chrome (50.0.2661.75) and Firefox (45.0.2).

![history_spam](https://cloud.githubusercontent.com/assets/35053/14752564/46872d8a-08d0-11e6-98c5-3bcd9eb38bec.png)

**Comment by timpritlove** [comment]
which "history" do you refer to?

**Comment by H4kor** [comment]
The Browser History ( chrome://history/ or Ctrl+H )

**Comment by fairsein** [comment]
Hi H4kor,

That is not a bug. It is a feature. We implement the timestamp of the audio file in the URL. So when you leave the page and come back, it brings you automatically to the point, where you were before. For the we change /#t=0:03.062 every 5 ms...

Best fairsein

**Comment by timpritlove** [comment]
No it's not a feature, it's a bug. A bug which we thought would be forgotten and ignored because of a new release of the web player. Which is still not there yet. So yes, it would be good to remove that "feature" from the old player.
