### ISSUE TITLE
Facebook Share has no Title

### ISSUE THREAD

**Issue by tasovi** [podlove/podlove-web-player#317]
Hi, when sharing an episode, Facebook can not read the title of the episode.
Instead it says, "no title".
thx for fixing that.

**Comment by eteubert** [comment]
In "Podlove > Modules", is the "Open Graph Integration" module active (should be active by default)?

If it is active and the problem doesn't go away, this is probably because you have another plugin installed that generates sharing fields that are in conflict with the Publisher (SEO plugin? Sharing plugins?).

**Comment by tasovi** [comment]
I deactivated the Open Graph Integration. No change unfortunately.
The only plugins I have activated are:
Akismet, Google Analytics Dashboard für WP, Impressum Manager, Podlove Podcast Publisher, Podlove Subscribe Button.
The rest I deactivated (like Social Media Feather and Add Meta Tags).
Any thoughts?

**Comment by eteubert** [comment]
The "Open Graph Integration" module _must be active_. Can you post a link to an episode?
Problem with Facebook sharing is also, that they only look at your website once and then always use what they found that first time, even if you change some settings (at least they keep/cache the data for a while before looking again).

**Comment by tasovi** [comment]
OK, I activated the Open Graph Integration again. No changes yet.
Here is a link to an episode:
http://pendler-podcast.de/episode-09-die-pendler-klinik-behandelt-prophylaktisch-drohende-beziehungsprobleme-der-pendler/

Thx for the help.

**Comment by BasicUserAccount42** [comment]
I don't think this issue has been resolved, and I also have a similar problem.  Any updates?

**Comment by alexander-heimbuch** [comment]
I closed this issue because it is not related to the web-player. If you still have problems with the Open Graph integration please reach out to the podlove-publisher folks.
