### ISSUE TITLE
Web player 3 beta displays artefacts of webplayer 2

### ISSUE THREAD

**Issue by nahlinse** [podlove/podlove-web-player#318]
I've updated my [podcast website](http://fiberthermometer.de/) (running polove publisher 2.3.12; no separate player plugin installed) to web player 3 beta yesterday. It looks pretty awesome :-)

One thing though is still not displayed properly: the "download" and "show URL" buttons are still being displayed as well as the related dropdown menu. 

Have you tried switching it of and on again? Yes, I did.
I have also tried to (temporarily) disable the download option - it doesn't make a difference.

![image](https://cloud.githubusercontent.com/assets/19305405/15179602/1d29e23c-177d-11e6-9274-34cf90bee2fe.png)

Any ideas?

**Comment by timpritlove** [comment]
The Download part is a separate shortcode. Just remove it from the Podlove template in use and it's gone.

**Comment by plutonik-a** [comment]
Hope, this will fix it. And btw, thanks for upgrading to 3 beta :) Looks great on your page.

**Comment by nahlinse** [comment]
It is MAGIC :-)

problem fixed!  :-)) Thanks for your quick help
