### ISSUE TITLE
web player iframe loads page recursive 

### ISSUE THREAD

**Issue by tompson** [podlove/podlove-web-player#319]
I tried to activate the Web Player 3 Beta in Podlove Expert settings but it does not load correctly, it loads the whole page again in the iframe

![e3a82f3c02bad8159eb9a1eee0a59d6cfe86399f_1_1690x1303](https://cloud.githubusercontent.com/assets/103224/15183454/6a50e592-1791-11e6-833a-2cdb368aa238.png)

**Comment by eteubert** [comment]
Can you try switching to a default theme (like twentysixteen) to see if the theme interferes with the loading?

**Comment by tompson** [comment]
no cache plugin
I am using twentythirteen - switching to twentysixteen does not make a difference

**Comment by eteubert** [comment]
Can you activate it again and leave it on for half an hour or so that I can have a look at the site?

**Comment by tompson** [comment]
I activated it - please have a look at http://dtr.fm/

**Comment by eteubert** [comment]
Thanks, I had a look, you can deactivate it again.
What I wanted to see is if the iframe is generated correctly, which it is:

```
<iframe src="http://dtr.fm/episode-83-republica-backup/?podloveEmbed=1" classname="podlove-webplayer-frame" style="height: 300px; width: 100%; border: none; overflow: hidden;"></iframe>
```

The question is why the embed parameter is ignored. I wonder if any plugin might be interfering. Can you provide a list of all active plugins?

**Comment by tompson** [comment]
The list of plugins is

Akismet
Jetpack
Flattr
Google Analyticator
wpMandrill
Podlove Podcast Publisher

**Comment by tompson** [comment]
I deactivated all and only left

Akismet
Jetpack
Podlove Podcast Publisher

still the same problem

**Comment by tompson** [comment]
could it be a problem with the rewrite rules? (.htaccess)

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

**Comment by eteubert** [comment]
Very strange. Rewrite rules look like the default ones everyone has and the plugins are also very common. Just to be sure, could you deactivate Jetpack too, since it does a lot of tiny changes depending on what modules are active?

Thanks for you assistance in finding the cause so far, but I still have no real clue what's the cause or how to fix it.

**Comment by tompson** [comment]
I deactivated everything and only left Podlove Podcast Publisher active - still no luck

**Comment by eteubert** [comment]
Anything in the PHP error logs (if you have access to them)?

I can offer you to debug it on your system if you create a WP Admin account for me and provide (s)FTP access to the Publisher plugin files (eric@ericteubert.de).

**Comment by tompson** [comment]
I found the problem, in my my main apache config file `AllowOverride None` was configured so the `.htaccess` file had no effect

I changed it to `AllowOverride All` and now it works

**Comment by eteubert** [comment]
Oh I see, that makes sense :)

**Comment by tompson** [comment]
thanks for your help!
