### ISSUE TITLE
V3 Download link does not start download

### ISSUE THREAD

**Issue by stenskjaer** [podlove/podlove-web-player#325]
In the player, when I click the download link, it does not start a download but simply starts playing the file in the player `iframe`.

Example: http://mirash.s3-website-us-east-1.amazonaws.com/recordings/11-2.html

Is that expected?

**Comment by eteubert** [comment]
Please see https://community.podlove.org/t/podlove-publisher-how-to-enable-force-downloads-fix-mime-types/78.
