### ISSUE TITLE
Browser-Verlauf wird vollgemüllt

### ISSUE THREAD

**Issue by Cok3Zer0** [podlove/podlove-web-player#331]
Zumindest beim Firefox wird für jede Änderung am Timestamp in der URL ein eigener Eintrag im Browserverlauf erzeugt.

**Comment by Kambfhase** [comment]
Bekannt. Siehe #316.

**Comment by Cok3Zer0** [comment]
Das war vor 8 Monaten! Es sollte zumindest abstellbar sein. 5ms sind Wahnsinn. 
Kann man nicht den Title updaten statt die Adresse?
