### ISSUE TITLE
v4 – GUI glitches

### ISSUE THREAD

**Issue by gitlik** [podlove/podlove-web-player#367]
**"30" not visually centered:** 

<img width="184" alt="screenshot 2017-04-27 18h 03m 32s" src="https://cloud.githubusercontent.com/assets/26041973/25492610/d484e93a-2b73-11e7-8393-9dccdeef4656.png">

**Proposal/idea:** 
Circled arrow left instead of normal Play triangle in REPLAY button? Because REplay is not Play.

<img width="155" alt="screenshot 2017-04-27 18h 05m 45s" src="https://cloud.githubusercontent.com/assets/26041973/25492747/416aad5a-2b74-11e7-94c3-d1f883e16aba.png">

**Ratio icon/font** 
could be finetuned, icons are quite big and weights are not well fitting to the words beside them. 
<img width="707" alt="screenshot 2017-04-27 18h 07m 45s" src="https://cloud.githubusercontent.com/assets/26041973/25492810/6c4e25a6-2b74-11e7-8d70-fe45373773c1.png">

**Volume**
1. I find the slider too many clicks away to quickly change volume. It is very prominent (aka learned behaviour) in every player of any kind.
2. I personally never use the player's volume, always change the system volume. IF we agree on this is the way to go anyway - why show a volume slider at all? 

**Remaining time**

<img width="763" alt="screenshot 2017-04-27 18h 09m 40s" src="https://cloud.githubusercontent.com/assets/26041973/25492887/b899c06e-2b74-11e7-9f12-ba849e68c6a1.png">
The remaining time is not distinguishable from the played time. Right now we have two similar numbers and the user has to find out by watching them (when playing not when paused!) which number means what exactly.
Also: learned behaviour (see: iTunes)

<img width="611" alt="screenshot 2017-04-27 18h 13m 53s" src="https://cloud.githubusercontent.com/assets/26041973/25493109/6022ad50-2b75-11e7-8041-ea7fb5967bb2.png">

Chapterlist complexity

<img width="785" alt="screenshot 2017-04-27 18h 15m 19s" src="https://cloud.githubusercontent.com/assets/26041973/25493160/8718f702-2b75-11e7-8728-45fd655fc4f3.png">

- What does the darker blue line do? Could it be removed by keeping the same functionality?
- The monospaced numbers on the right have a different size than the titles they are referring to, but only slightly. I also find the zeros with lines techie and a bit confusing.
- In maximum width of the player, the distance to the time numbers is much to far for the eye to follow. Maybe introduce a connecting element (see any app that deals with lists for a reference)?
- When the player is at its smallest size, titles and numbers are too close and need a little space between them for differentiation

<img width="256" alt="screenshot 2017-04-27 18h 19m 28s" src="https://cloud.githubusercontent.com/assets/26041973/25493367/34e69ac4-2b76-11e7-8fc4-67f814947b70.png">

**Comment by alexander-heimbuch** [comment]
@gitlik Could you split the issues into separate issues so we can decide between bugs and feature requests. Also it is much easier to assign the issue to a specific person :)

**Comment by gitlik** [comment]
How would I do that? Justediting this issue and c/p the stuff somewhere else?

**Comment by alexander-heimbuch** [comment]
Yep, you have to c/p and create new issues.

**Comment by gitlik** [comment]
Done. Can I delete this one?

**Comment by alexander-heimbuch** [comment]
Sure, thank you
