### ISSUE TITLE
Custom Share Endpoint

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-web-player#441]
Provide an config option to provide a custom share endpoint:
```
reference: {
  share: "http://foo.bar/share"
}
```

**Comment by eteubert** [comment]
To clarify: the reference.share endpoint config exists already but it only expects the URL to the `share.html` and the player adds the episode config URL itself. I would like and endpoint that is taken as it is, where I add the episode config myself. As an example from the Publisher: `http://publisher.dev/podlove/player/4/84/` would redirect to the `share.html` and already include the config URL.
