### ISSUE TITLE
Webplayer 4 (Alpha): Indication error with last chapter mark (sometimes)

### ISSUE THREAD

**Issue by pommes** [podlove/podlove-web-player#444]
Hi Web-Player Developers,

in some cases Webplayer 4 (Alpha) has indication errors with the last chapter marks on my episodes.   I'm using Podlove Publisher 2.6.2 and using chapter mark files as assets created by _Ultraschall_.

Screenshot of chapter mark indication error
![podlove-player-4-alpha-last-chapter-time-broken](https://user-images.githubusercontent.com/1306595/31195799-bae0787c-a94b-11e7-87fe-6f6c0a81dc7e.png)

Entries in chapter mark file
```
00:00:00.000 yyy Podcast: State of the Union
00:00:18.107 Motivation
00:01:04.310 Die Lösung: xxx Cloud
00:02:18.714 Neue Landing Page
00:02:47.001 Anleitung zum Abonnieren mit dem Smartphone
```

Kind regards
Tim

**Comment by alexander-heimbuch** [comment]
Hey Tim,

this bug may have been resolved with Webplayer 4 beta release. Should be available with the next publisher release.
