### ISSUE TITLE
Webplayer does not play in Chrome

### ISSUE THREAD

**Issue by screechiie** [podlove/podlove-web-player#451]
Webplayer does simply not play in Chrome, but works with other webbrowsers. 

Website: www.radioRAW.de
Tested with:
Podlove Podcast Publisher 2.6.2
Windows 7 and 10
Android
Chrome

Any ideas? Am I the only one with that problem?

**Comment by alexander-heimbuch** [comment]
Hey,
you are using the deprecated version 3, either switch to LTS Player 2 or to beta Player 4

**Comment by alexander-heimbuch** [comment]
Glad to hear but stay tuned for version 4 release :D
