### ISSUE TITLE
Chrome for iOS: Doesn't resize on mobile Viewport.

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-web-player#461]
![](https://community.podlove.org/uploads/podlove/original/1X/d7b5b0d929ada3c02f8f0807cee88986af7265cf.png)

**Comment by dnebannoS** [comment]
I experience the same problem with Safari for iOS (running webplayer alpha thats comes with Podlove Publisher 2.6.2; iOS 11.1.1).

![webplayer_size_bug](https://user-images.githubusercontent.com/4618869/32693187-dbf598dc-c726-11e7-960d-0a9aaa67d078.png)

**Comment by alexander-heimbuch** [comment]
@dnebannoS for iOS this should be fixed since v4 beta. Publisher 2.6.2 only provides alpha versions. With 2.7 you will be able to use the v4 beta and above :)

**Comment by alexander-heimbuch** [comment]
@dnebannoS can try out the latest version of web player and see if the bug is still present?

**Comment by dnebannoS** [comment]
Sorry for the late reply. Yes, the bug is fixed with the player that comes with Podlove Publisher 2.6.3 (for some reason it says "Web Player Version: no web player found" under "Podlove > Help" in my Wordpress installation)

**Comment by alexander-heimbuch** [comment]
That is a publisher related issue :( Unfortunately I can't help you with that.

**Comment by Inrumpo** [comment]
This looks like being fixed by now. At least for people running the beta. Can anybody else confirm?

**Comment by DanielBaulig** [comment]
I'm running  Podlove Publisher 2.8.6 with the web player loaded from CDN. I am running into this same issue on Chrome and Safari on iOS. When using Desktop Chrome with mobile device emulation, I do not have any problems.

**Comment by alexander-heimbuch** [comment]
@DanielBaulig  Can you share a link to the page?

**Comment by DanielBaulig** [comment]
https://www.happilyunmarried.media

**Comment by alexander-heimbuch** [comment]
Hmm, can't really reproduce the issue :/

![image](https://user-images.githubusercontent.com/7794717/58074305-3fb29800-7ba5-11e9-88c3-1398b28e9761.png)
Chrome 74

![image](https://user-images.githubusercontent.com/7794717/58074353-61ac1a80-7ba5-11e9-8b9d-2f2abf02a926.png)
Safari 12.1

**Comment by DanielBaulig** [comment]
On iOS? As I mentioned, I wasn’t able to reproduce the issue on desktop browsers myself. Only on the iOS browsers.

**Comment by alexander-heimbuch** [comment]
Ahh sorry didn't read that, will have a look.

**Comment by alexander-heimbuch** [comment]
Ok, turns out you have custom css, that overwrites the sandbox styles. Removing this fixes the player width:
![image](https://user-images.githubusercontent.com/7794717/58117986-2db21300-7c00-11e9-8ddf-23fb022589ba.png)

**Comment by DanielBaulig** [comment]
@alexander-heimbuch Thank you. This CSS came from the OceanWP theme. I removed it and that fixed the problem. Greatly appreciate you help here!
