### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-web-player#462]
Some characters don't get displayed correctly in the new player 4 beta. 

![letter escaping](https://user-images.githubusercontent.com/11300164/32235264-441ef500-be5f-11e7-9a9c-9a672dc0dc50.png)
(Safari on iOS 10.3.3, iPhone SE)
Found here: http://bcsweekly.theinsnider.de/s3e10-lantern/

**Comment by alexander-heimbuch** [comment]
Seems more like an encoding issue to me while creating the configuration:
`subtitle: 'Finale, ohoho! Wait &#8230; letzte Folge! Wieder ein Jahr warten \/o\\',`

@eteubert Could you have a look?

Full config:
```
podlovePlayer('#podlovewebplayer_830c31539c34193229d71b8a949283f0c786e630', {
  show: {
    title: 'Better Call Saul Weekly',
    subtitle: 'Ein deutschsprachiger Podcast zur Serie',
    summary: 'Wir besprechen hier Folge f\u00fcr Folge das Breaking Bad Spin-Off "Better Call Saul" von Netflix',
    poster: 'http:\/\/bcsweekly.theinsnider.de\/wp-content\/cache\/podlove\/e1\/edcae804c532ceb30a662c862a83bb\/better-call-saul-weekly_500x500.png',
    link: 'http:\/\/bcsweekly.theinsnider.de'
  },
  reference: {
    base: 'http:\/\/bcsweekly.theinsnider.de\/wp-content\/plugins\/podlove-podcasting-plugin-for-wordpress\/lib\/modules\/podlove_web_player\/player_v4\/dist',
    share: 'http:\/\/bcsweekly.theinsnider.de\/wp-content\/plugins\/podlove-podcasting-plugin-for-wordpress\/lib\/modules\/podlove_web_player\/player_v4\/dist\/share.html',
    config: 'http:\/\/bcsweekly.theinsnider.de\/?podlove_player4=198'
  },
  theme: { main: '#cccccc', highlight: '#000' },
  title: 'S3E10 - Lantern',
  subtitle: 'Finale, ohoho! Wait &#8230; letzte Folge! Wieder ein Jahr warten \/o\\',
  summary: 'In gro\u00dfer Besetzung besprechen wir das Finale der dritten Staffel und ziehen unser Fazit dazu und zur Staffel insgesamt. Zwischendurch geben wir euch unser lokales Wetter durch und der Florian meldet sich mit einem Audio Kommentar aus New York.<br \/>\r\n<br \/>\r\nDenkt an das Gewinnspiel: hinterlasst einen Kommentar zu dieser oder der letzten Folge und es gibt ein kleines Better Call Saul Stickerpack zu gewinnen!',
  publicationDate: '2017-06-24T01:26:49+00:00',
  poster: 'http:\/\/bcsweekly.theinsnider.de\/wp-content\/cache\/podlove\/e1\/edcae804c532ceb30a662c862a83bb\/better-call-saul-weekly_500x500.png',
  duration: '02:28:53.216',
  link: 'http:\/\/bcsweekly.theinsnider.de\/s3e10-lantern\/',
  audio: [
    {
      url: 'http:\/\/bcsweekly.theinsnider.de\/podlove\/file\/416\/s\/webplayer\/c\/episode\/s3e10-lantern.m4a',
      size: '91446293',
      title: 'MPEG-4 AAC Audio (m4a)',
      mimeType: 'audio\/mp4'
    },
    {
      url: 'http:\/\/bcsweekly.theinsnider.de\/podlove\/file\/415\/s\/webplayer\/c\/episode\/s3e10-lantern.mp3',
      size: '107391252',
      title: 'MP3 Audio (mp3)',
      mimeType: 'audio\/mpeg'
    }
  ],
  chapters: [],
  contributors: [
    {
      name: 'MacSnider',
      avatar: 'http:\/\/bcsweekly.theinsnider.de\/podlove\/image\/68747470733a2f2f7777772e67726176617461722e636f6d2f6176617461722f61306130383265343234393761373963353435363265653865356663626238302e6a70673f733d35313226643d6d6d26723d67\/150\/150\/0\/macsnider',
      role: null,
      group: null,
      comment: null
    }
  ]
})
```

**Comment by eteubert** [comment]
What exactly did you use as subtitle? Using `…` renders correctly for me.

**Comment by Inrumpo** [comment]
The example is not from one of my podcasts. I had the same issue over at `https://rueckschau.news`. It was a `...` as well. (Just changed it to `.` for now.) 
I'll do some further testing. But I can't right now. Updating to build 449 made our player v4 disappear (after the plugin itself disappeared as well ^^). I had to use v2 as a fallback until we get it up and running again. /cc @loewe88

**Comment by alexander-heimbuch** [comment]
What do you mean with disappear?

**Comment by Inrumpo** [comment]
The player will not be displayed anymore. Not even the preview below the settings. V2, V3 & Podigee are working though. The repair-button did not help. We don't use a caching plugin. 

Concerning the "disappearance" of the plugin itself: I don't know what happened there while updating to build 449. Unfortunately, I forgot to make a screenshot of the error message. Maybe @loewe88 can add some insight in due time.

**Comment by alexander-heimbuch** [comment]
Ok, if you have some more details please keep us posted

**Comment by Inrumpo** [comment]
We've now updated the Podlove beta to `2.7.0.build451`. This time everything worked fine and the player v4 is working again. ¯\_(ツ)_/¯

Back on topic:
Now I've been able to test this issue again. `...` will lead to `&#8230;`. But: The "tripple dot symbol" `…` does render fine. Three _individual_ dots will lead to `&#8230;`.
And `&` does render as `&#038;`.
I've also tested `#`, `§`, `ä`, `ß`, `$`, and `€`. Those do render fine.

**Comment by eteubert** [comment]
Ah, I now only realize that this applies only for the subtitle, not for the title (at least for me). Looking into it now :)

**Comment by eteubert** [comment]
Turns out I was escaping it on purpose. Fixed in build452.

**Comment by eteubert** [comment]
Can you confirm this was fixed?

**Comment by Inrumpo** [comment]
Just tested it. Yes, the issue is fixed.
