### ISSUE TITLE
Jump to specific time via link on current page

### ISSUE THREAD

**Issue by cweiske** [podlove/podlove-web-player#465]
I've made a transcription for logbuch netzpolitik 232, and wanted to add play buttons to single sentences.

What's the correct way to cause the player on the current html page to jump to a given time?

Links:
- http://tmp.cweiske.de/lnp232.html
- https://github.com/cweiske/podcast-transcriptions/tree/master/Logbuch%20Netzpolitik/LNP232%20Der%20b%C3%B6se%20Kleber%20aus%20Deutschland

**Comment by alexander-heimbuch** [comment]
For example: https://logbuch-netzpolitik.de/lnp232-der-boese-kleber-aus-deutschland?t=00:48

**Comment by cweiske** [comment]
Yes, this is from external links.

But I imagine that my HTML gets added to that LNP blog post page, and the currently playing web player should be controlled. The URL you suggested would reload the page, which is not desired.

The player should be controlled without reloading.

**Comment by alexander-heimbuch** [comment]
In general this is not supported by the player. The timestamp is parsed on player init. You can control the player completely if you integrate it by yourself, please see the advanced documentation section: http://docs.podlove.org/podlove-web-player/advanced.html

If you are planning to add transcriptions, I'm currently developing a native player feature to provide transcriptions.

**Comment by cweiske** [comment]
Ok, so I have to disable those jump buttons :/
