### ISSUE TITLE
Script Error by New Post

### ISSUE THREAD

**Issue by RickorDD** [podlove/podlove-web-player#466]
when i starte a "New Post" then is a JS Error. 

<img width="370" alt="bildschirmfoto 2017-11-16 um 09 04 18" src="https://user-images.githubusercontent.com/6922544/32880458-065914a2-caae-11e7-9405-8dd0f2838e4a.png">

<img width="461" alt="bildschirmfoto 2017-11-16 um 09 02 37" src="https://user-images.githubusercontent.com/6922544/32880311-7ee0148a-caad-11e7-8cbd-5838fcaae94a.png">

**Comment by alexander-heimbuch** [comment]
This affects Web Player Version 2, please file a ticket in the [corresponding repo](https://github.com/podlove/podlove-web-player-v2). This repo is for the latest Web Player version (currently 4).
