### ISSUE TITLE
Audio-Tab: Cookie doesn't seem to remember actual Volume

### ISSUE THREAD

**Issue by heysl** [podlove/podlove-web-player#467]
The webplayer remembers setting the volume to another value, let's say 25%, so reloading the page some time later, the volume setting will still be at 25%.

However, the actual volume seems to be on 100% after reloading the page. What you can hear is definitely not a value of 25% and if you adjust the volume slider a little upwards, say from 25% to 30%, you can hear a significant **drop** of actual volume.

**Comment by alexander-heimbuch** [comment]
Thanks for the report, I will investigate.
