### ISSUE TITLE
Enable URLs/links in chapters

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-web-player#470]
We can include URLs in chapters.
V2 is using this information to generate links. V3 and V4 seem to have abandoned this functionality. The Podlove backend still does support this. 
I'd like to see this feature coming back.

**Comment by alexander-heimbuch** [comment]
Also chapter images aren't supported yet but should be :)

**Comment by Inrumpo** [comment]
The link feature has been added to version 4.1.7 (or even before). Thanks! 
However, links are not yet visible while viewing on a smaller device.
