### ISSUE TITLE
Poster in jpeg

### ISSUE THREAD

**Issue by swschilke** [podlove/podlove-web-player#474]
Hallo,

laut der Doku für Standalone Nutzung sieht es so aus, als ob das Poster in png sein muss. Geht auch jpeg?

Vielen Dank

.

**Comment by swschilke** [comment]
Ok weitere Doku gefunden und dort wir jpeg verwendet

**Comment by alexander-heimbuch** [comment]
Alles was ein `img` tag fressen kann. Falls du es ausprobieren möchtest, der Playground eignet sich sehr gut dafür: https://docs.podlove.org/podlove-web-player/playground.html 

![kapture 2017-12-18 at 9 08 02](https://user-images.githubusercontent.com/7794717/34095776-1082f676-e3d3-11e7-8fc3-1a8b4dab2f5e.gif)

**Comment by swschilke** [comment]
#Danke
