### ISSUE TITLE
No audio assets to download when video asset is active

### ISSUE THREAD

**Issue by hinnerkweiler** [podlove/podlove-web-player#476]
Hi,
I just enabled an additional asset in recent episodes to offer a download for the video I put on youtube recently and came across this issue in the Web-Player's Download Section on http://segelradio.de:  

**Expected:**
Being able to make a coice from all episode media file formats (m4a, mp3 or mp4) from the dropdown list and download media asset. 

**Actual:**
When mp4 asset is enabled no other assets are shown in the dropdown list and only the mp4 can be downloaded.

<img width="1084" alt="1 - assets for episode" src="https://user-images.githubusercontent.com/18248862/34457182-9ea0fbd0-eda9-11e7-9460-9478b1952a7e.png">

Downloadable

<img width="652" alt="2 - only video can be downloaded" src="https://user-images.githubusercontent.com/18248862/34457180-9a096f12-eda9-11e7-81d1-bbe3d999f14b.png">

**Workaround:**
Disable the video asset and the audio assets are shown again

<img width="1094" alt="3 - disable video asset" src="https://user-images.githubusercontent.com/18248862/34457176-89fefba0-eda9-11e7-9aae-c97a75c9ef76.png">

Downloadable

<img width="638" alt="4 - other assets can be downloaded" src="https://user-images.githubusercontent.com/18248862/34457178-8f37052c-eda9-11e7-93c4-50cb2ed375fc.png">

**Site Details:**

Website                    http://www.segelradio.de
PHP Version                7.0.22-0ubuntu0.16.04.1
WordPress Version          4.9.1
WordPress Theme            Voyager v1.4.3
WordPress Database Charset utf8
WordPress Database Collate 
Publisher Version          2.6.3
Web Player Version         no web player found
Twig Version               1.35.0
open_basedir               ok
curl Version               7.47.0
iconv                      available
simplexml                  ok
max_execution_time         600
upload_max_filesize        20M
memory_limit               768M
disable_classes            
disable_functions          pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
permalinks                 ok (/%postname%/)
podlove_permalinks         ok
podcast_settings           ok
web_player                 ok
podlove_cache              on
assets                     
  - m4a    audio/mp4        http://www.segelradio.de/feed/m4a/
  - mp3    audio/mpeg       http://www.segelradio.de/feed/mp3/
  - jpg    image/jpeg       no feed
  - psc    application/xml  no feed
  - mp4    video/mp4        no feed
  - json   application/json no feed
cron                       ok
multisite                  Podlove Publisher is not activated in main blog!

**Comment by alexander-heimbuch** [comment]
Interesting. I would guess that this is an Publisher related issue. The player only reflects the config it gets. @eteubert Can you investigate?
