### ISSUE TITLE
Transcripts 

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-web-player#482]
- ~~Follow button in Safari abgeschnitten~~
- ~~Play bei gescrollten transcripten~~
- ~~Mehr rand~~
- ~~Hover am wort~~
- Wortgenaue Auflösung
- ~~erste und letzter Transkript um Kapitelmakre zappelt~~
- ~~Initialer render bei tab wechsel fehlerhaft~~
- Indikator position
- ~~Links ausgerichtet such position~~
- ~~Doppelpunkt weg bei speakern, Abstand vergrößern~~
- ~~Suchfeld im kleinen modus bei interaktion aufziehen~~
- Textgröße dynamisch

**Comment by stuwillis** [comment]
Transcripts are showing strangely on our player: [http://draft-zero.com/2018/dz-49](http://draft-zero.com/2018/dz-49)

**Comment by alexander-heimbuch** [comment]
Can't see a Web Player 4 on your site.

**Comment by stuwillis** [comment]
Yes, my mistake, I am using the Wordpress plugin.  :-/ Looking forward to Web Player v04.
