### ISSUE TITLE
Download Episode Related Content

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-web-player#485]
# User Stories
## Audio Files
As a User I want to be able to download the episode in order to hear it offline or to archive it.

## Marketing Material
As a User I want to be able to download PDF handouts for an episode in order to print and share it with others.

## Additional Material
As a User I want to be able to download additional material like transcripts, videos and other dynamic content in order to get more complementary information.

# Current Implementation
![image](https://user-images.githubusercontent.com/7794717/39968600-fc219fe6-56cf-11e8-8331-3367dd80b0be.png)
The existing implementation only allows to download audio files. Other media types are potentially available but aren't visualised.

# Requirements
* All downloadable material should be visualised in the "Download Tab"
* Material should be organised by type
* Design should allow dynamic content

# Design
![image](https://user-images.githubusercontent.com/7794717/47430998-32facc80-d79b-11e8-8126-3f8e38af72e4.png)
https://www.figma.com/file/QmubQucvL2qYtHLzhSRIFtrj/Web-Player?node-id=0%3A1

**Comment by coolcut** [comment]
@alexander-heimbuch Looks good to me. Maybe there will be some follow-up questions down the road, but from my point of view, it sounds clear. Hopefully, I can deliver something until early next week. I will keep you updated. 😄

**Comment by jgerhold** [comment]
@alexander-heimbuch Is there an example with additional media files? At the moment there are only audio files in the standalone example. What files will be grouped? Automatically via the media type of the mime type + an exceptions list for things like for example "application/pdf"?

**Comment by alexander-heimbuch** [comment]
@jgerhold Yes, right now only audio files are available. Later on this should be only one list of files that are fileterd by ther mimeType, as you suggested. Btw. I implemented that yesterday :D So @eteubert we should talk about what files are available right now.

**Comment by eteubert** [comment]
@alexander-heimbuch see https://github.com/podlove/podlove-publisher/blob/master/includes/setup.php#L29

**Comment by alexander-heimbuch** [comment]
@eteubert nice, can you add these as `files` to the player initial configuration?

**Comment by eteubert** [comment]
Sure, how? https://docs.podlove.org/podlove-web-player/config.html only mentions audio files

**Comment by alexander-heimbuch** [comment]
I will create a release with the correct configuration. The Player will still accept audio as a valid configuration to be compatible with older configurations.

**Comment by jgerhold** [comment]
@alexander-heimbuch If you still want help with this a part of this issue… I'm happy to take a look.

**Comment by alexander-heimbuch** [comment]
@jgerhold sure :D if you could give me some hints how familiar you are with redux/vue I can suggest you some matching issues :)

**Comment by jgerhold** [comment]
@alexander-heimbuch I’ve done some vue/vuex projects. redux/redux-vuex is a little bit different, but  does not look very complicated. So any starter-issues are welcome.
