### ISSUE TITLE
Improve Audio Tab

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-web-player#488]
### User Story
As a User I want to adjust audio related settings in order to align them to my personal needs

* Thumbs larger
* ~~Double click moves to 100%~~
* Marker in Speed
* Magnetic Markers
* Mono audio playback #623

### Design
<img width="469" alt="screenshot 2018-10-24 at 14 35 47" src="https://user-images.githubusercontent.com/7794717/47430632-3d689680-d79a-11e8-913f-fb31af1543f9.png">

* https://www.figma.com/file/QmubQucvL2qYtHLzhSRIFtrj/Web-Player?node-id=148%3A95

**Comment by jnnkm** [comment]
Hi everybody! Thank you for this fine Project, I really like it!

I would like to offer help on the AudioTab Improvements, I already played around in the Code a little bit
and I’m encountering some Issues with the TestSuite.

So I added some functionality to src/components/shared/InputSlider.vue for the doubleclick feature, and added some tests in cypress/integration/tab-audio.spec.js

But I can’t get the tests to run:

- „yarn test“ seems to execute all the tests, but is always successful, even when the code is broken on purpose.
- yarn cypress:dev is generating some not very useful output (see screenshot)

Am I missing out on something? How to run the tests on a local machine?
<img width="1180" alt="bildschirmfoto 2018-06-21 um 15 37 19" src="https://user-images.githubusercontent.com/6465434/41728491-3c66ad2e-7577-11e8-93bb-0f654fa5780e.png">

**Comment by jnnkm** [comment]
Hi Hi, 
thanks for merging my last PR :)

I’d be happy to take this Issue further, the only Problem I’m facing at the moment is:

- How is a magnetic marker supposed to look like / behave? 
- How do you imagine a marker in speed ? Something like a indicator where the 100% mark on the speed input is?

It’d be great if you could provide some example or further description to make these issues more clear 👍

**Comment by alexander-heimbuch** [comment]
@jnnkm Maybe @coolcut can help with a Design for that :)

**Comment by coolcut** [comment]
I can definitely take a look at this. As @jnnkm already said, a little bit more information would be great. I suppose your understanding of "magnetic markers" are predefined defaults on a slider, right?

Besides the meaning/behavior of the slider, I would also challenge the assumption that a slider is the best solution for something like playback speed. Maybe some reasonable defaults (more "button/tabs"-like) could also do the trick and are faster/more accessible. Just some random ideas - I will think about it over the next couple of days and follow-up on this.

**Comment by alexander-heimbuch** [comment]
Yes magentic markers are predefined values within the slider range, the pointer will snap into these areas. We iterated over different ways how to change especially the rate but were always falling back to a slider solution. The reason behind that is that especially rate is highly subjective and can vary between 50% and 400%. But I'm open for any new ideas in this area :)

**Comment by alexander-heimbuch** [comment]
Check back the Audio API if we can detect mono/stereo
