### ISSUE TITLE
Firefox: episode starts playing rather than downloading

### ISSUE THREAD

**Issue by lnw** [podlove/podlove-web-player#544]
I'm not sure if this is a bug or a misconfiguration.

My browser is Firefox 52.6 on debian linux.

On some sites (eg wochendaemmerung.de) klicking Download --> Download episode plays the episode in the browser.  I don't expect that's ever intended.  Other sites down have that problem (eg logbuch-netzpolitik.de).  Is that a misconfiguration?  Could the web player be made safe against that?

cheers, lukas

**Comment by alexander-heimbuch** [comment]
Its kind of both :) For server side: https://community.podlove.org/t/podlove-publisher-how-to-enable-force-downloads-fix-mime-types/78

On Player Side: https://github.com/podlove/podlove-web-player/issues/502 (is already fixed and integrated, will be published in next release)

**Comment by lnw** [comment]
Great, thank you!
