### ISSUE TITLE
Warnings before first save of settings

### ISSUE THREAD

**Issue by Rinma** [podlove/podlove-web-player#569]
Before I save the first time the settings i get a lot of warnings. Also all the default values are only displaying the first char like “a” from “audio/mpeg”.

The warnings are:
Warning: Illegal string offset ‘main_poster’ in /homepages/htdocs/app/wp-content/plugins/podlove-web-player/settings.php on line 167

Warning: Cannot assign an empty string to a string offset in /homepages/htdocs/app/wp-content/plugins/podlove-web-player/settings.php on line 167

Warning: Illegal string offset ‘main_poster’ in /homepages/htdocs/app/wp-content/plugins/podlove-web-player/settings.php on line 169

Steps to reproduce:
* Install version 2.1.0 of this plugin
* Open the settings page

**Comment by alexander-heimbuch** [comment]
Hey @Rinma,

Web Player 2.1 Plugin is currently not under maintenance. But I'm currently working on a next release.
