### ISSUE TITLE
Add posibility to customize visibleComponents in shortcodes

### ISSUE THREAD

**Issue by KSDaemon** [podlove/podlove-web-player#570]
Hi all! First of all, thanks for great work!

I've digged through all the docs and google, but can not find any info about possible options for customizing web player configuration. I'm using WP Podlove Podcast Publisher plugin. 
I want to be able to customize `visibleComponents` options for player instance.
Is it possible?

**Comment by alexander-heimbuch** [comment]
Hey @KSDaemon,

with the Publisher that's currently not possible. BUT I'm working on a standalone plugin with a configurator included. After release hopefully the transition to the publisher should be easy.

**Comment by KSDaemon** [comment]
@alexander-heimbuch Thanks for answer! Looking forward for release! :)
