### ISSUE TITLE
IE11: "Promise not defined", player does not render

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-web-player#574]
I received the following error report from a user using IE11.0.9600 on Windows.

![promise-not-defined](https://user-images.githubusercontent.com/235918/38332131-7f037298-3855-11e8-84e2-d6d2bef149d0.jpg)

**Comment by circuscode** [comment]
A user, that's me. 
If you have questions or need for information regarding this issue, contact me.
marco.hitschler@unmus.de
Affected URL:
https://www.unmus.de/zirkus011-weihnachtlicher-fruehling/

**Comment by circuscode** [comment]
I checked the webplayer on other Podcast sites like Raumzeit from Tim. 
The Player will also not rendered there.

**Comment by leonidlezner** [comment]
The same problem here. IE 11.0.9600, Win 7.

`SCRIPT5009: 'Promise' is undefined`

**Comment by circuscode** [comment]
Curiously the embeded version of the webplayer will be rendered with IE11 (but with some strange UI effects).

**Comment by entttom** [comment]
How did you solve the problem? On tim’s websites (cre, freaks how) and also in mine it’s still not working. But when I visit your site with ie11 the player appears.
