### ISSUE TITLE
Chapter select

### ISSUE THREAD

**Issue by amoksep** [podlove/podlove-web-player#577]
If i am select a chapter it start always at the beginnen of this chapter.
But i expected: if i clicked in the middle of a chapter -> player jump to this point

seen in Chrome Version 65.0.3325.181, Firefox 59.0.2 (64-Bit)

edit:
  the mouseover looks correct. 
      the time in player is updating correct

**Comment by alexander-heimbuch** [comment]
This is an advanced interaction we recently introduced. If you press alt + click it should work as you expect it.
