### ISSUE TITLE
[Request] Don't show download options if there is only one

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-web-player#603]
I have a small feature request, nothing of high priority:

The webplayer `V4.0.9` shows download file format options, even if there is only one option available. This is redundant.
![pwp download options](https://user-images.githubusercontent.com/11300164/39495224-c7615d9e-4d99-11e8-9114-ed0a979edbe0.png)

Please only show download file format options, if there is more than one. 

I'm currently using the webplayer `V4.0.9`.

Feed is at `https://gametalk.fm/feed/m4a/ ` and `https://gametalk.fm/feed/mp3/` (discontinued & redirected).

**Comment by alexander-heimbuch** [comment]
Will be solved with the changes in #485
