### ISSUE TITLE
[Request] Global Hotkeys for Podlove-Player

### ISSUE THREAD

**Issue by Voigit** [podlove/podlove-web-player#616]
Would it be possible to implement definable global hotkeys for the podlove player for play and pause?
This would especially great because I have dedicated Multimediakeys on my Keyboard, which are precisly for Play/Pause of Music, and this is why I still use WinAmp to play most of my Podcasts.

**Comment by alexander-heimbuch** [comment]
The player already supports some shortcuts. Space plays/pauses the player. You can scrub to the timeline using left and right arrow. With `alt` + `right arrow` and `alt` + `left arrow` you can jump between chapters.

**Comment by Voigit** [comment]
Yeah these are the standard local Hotkeys, but a global definable Hotkey for Play/Pause would still be something I would like to se.

**Comment by alexander-heimbuch** [comment]
Actually this is not really a problem of the player, it is more related to the browser. The browser will only trigger keyboard events on focused elements. That's why you can't minify the browser and still send keyboard events to it.
