### ISSUE TITLE
Mono audio playback

### ISSUE THREAD

**Issue by Foaly** [podlove/podlove-web-player#623]
Hi! First of all thanks for this amazing project and the many hours of joyful listening 😃 
I have an accessibility feature request. For auditory impaired people that don't have stereo listening, it would be really useful to have an option to downmix the audio output to mono. Of course usually those people have a setup, that only outputs mono on the sound card side, but having this option in the webplayer would make it easier on devices that are not your own. I would love to see a checkbox in the audio tab to switch to mono sound output!

**Comment by Foaly** [comment]
Thank you so much! I think especially for the single sided deaf this will be very useful! 😀 
I know a bit of javascript myself and I do a lot of audio programming, but I don't know vue.js and digging around I got confused 😄 I think it should be doable using the web audio API, maybe if somebody points me in the right direction I could try to help.

**Comment by alexander-heimbuch** [comment]
Help is always appreciated 👍  I extracted the audio driver here: https://github.com/podlove/html5-audio-driver This will also be the place for this kind of functionality. I was planning to add some kind of `filters`. If you have questions don't hesitate to ask :)

**Comment by Foaly** [comment]
Ah I see! I will have a look there. [The AudioNode channelInterpretation](https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/channelInterpretation) seems to be the thing that could do the job automagically.

**Comment by alexander-heimbuch** [comment]
Released in 4.2.0

**Comment by Foaly** [comment]
Awesome thank you! I have seen some players with version 4.2.4 out there, but none of them seem to have this feature. Is it something that is not enabled by default?

**Comment by alexander-heimbuch** [comment]
Hey,
I implemented the mono feature using WebAudio API (https://github.com/podlove/html5-audio-driver/blob/master/src/filters.js) and also enabled it in the first run. Unfortunately I had to realise that using WebAudio enforces CORS. Many podcasters host their podcast files on different domains so this wasn't an option :(

**Comment by Foaly** [comment]
Ah I see, thats unfortunate. So does that mean the feature won't be able to be used this way unless all the podcasters use "correct" resource management or is there another way this could be implemented?
