### ISSUE TITLE
Problems with m3u / x-mpegURL 

### ISSUE THREAD

**Issue by eazyliving** [podlove/podlove-web-player#713]
Hiho,

to avoid having trouble with mixed content (http / https) on fyyd.de, I'd love to use m3u style URLs for the player.

This is the point where I fail :) The player doesn't take the audio inside the m3u. Here's a demo:

https://fyyd.de/pwp41-issue

Player 1: Original Audio-URL with correct mimetype (mp4)
Player 2: m3u-URL with wrong mimetype mp3 (since I saw it running with that, but can't get it to work again)
Player 3: m3u-URL with correct mimetype x-mpegURL.

P1 works, P2 doesn't, P3 doesn't but tells you before even clicking the play button.

Any idea? The m3u's URL is https://alexa.fyyd.de/s2as/2869354

**Comment by alexander-heimbuch** [comment]
Sorry for the late response. The provided m3u file contains only a single url. I don't know if that is valid, all m3u files I tested with also contained an extension info.

**Comment by alexander-heimbuch** [comment]
@eazyliving still an issue?
