### ISSUE TITLE
Cant load Podlover Player with IE 11.0.9600

### ISSUE THREAD

**Issue by entttom** [podlove/podlove-web-player#737]
I cant load the Podlove player with IE 11.0.9600.

This error appears:
https://pasteboard.co/HzzXtwX.jpg

Or this:
SCRIPT5: Zugriff verweigert
Datei: button.html, Zeile: 1, Spalte: 1

https://www.kofferkinder.com/asien/andamanensee-koh-lipe-koh-mook-muk/

Can someone explain this to me? What im doing wrong?

**Comment by alexander-heimbuch** [comment]
Hey, I added a method to fall back to the basic html5 audio element player for integrations. Podlove Publisher will provide this soon so we can also cover browsers that aren't supported.
