### ISSUE TITLE
Don't display the duration if it is not defined initially

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-web-player#844]
![image](https://user-images.githubusercontent.com/7794717/48534735-4801e180-e8a9-11e8-8514-744091d1f31a.png)

In the initial state it will display a duration of `00:00:00` if it is not defined. This information is misleading, instead a normal play button should be displayed.

**Comment by alexander-heimbuch** [comment]
@herrmannplatz this could also be a good starter for you

**Comment by herrmannplatz** [comment]
Perfect. Managed to get it running. Will check over the weekend.

And thanks for add the the label 👍
