### ISSUE TITLE
Replace superagent dependency with native fetch

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-web-player#849]
We support the latest 2 browser versions with the Webplayer, all of these browsers support [fetch](https://caniuse.com/#search=fetch).

**Comment by texhnolyze** [comment]
Since the previous pull request for this failed deployment and integration tests and wasn't merged I suppose you wouldn't mind if I have a look at implementing this?

**Comment by alexander-heimbuch** [comment]
Development moved to this repository: https://github.com/podlove/ui in there I already migrated the changes :)
