### ISSUE TITLE
Userland "runtime" options are not merged with defaults

### ISSUE THREAD

**Issue by jdreesen** [podlove/podlove-web-player#858]
The docs say that it's possible to set some [runtime options](https://github.com/podlove/podlove-web-player/blob/development/docs/config.md#runtime). 

But when the key `runtime` is present in the userland config it'll [overwrite](https://github.com/podlove/podlove-web-player/blob/development/src/app.js#L13-L16) the default `runtime` config, which breaks<sup>1</sup> several things because all keys of the default config get replaced by the ones given in the userland config. 

The problem is, that it's not really desired to determine some of the values by hand (such as [the clients `browser` or `platform`](https://github.com/podlove/podlove-web-player/blob/development/src/utils/runtime.js#L17-L18)) or doesn't even make sense (like the [`version`](https://github.com/podlove/podlove-web-player/blob/development/src/utils/runtime.js#L16)).

When I set the `language` config key to `'de'`<sup>2</sup>, the other `runtime` config information is lost. 
To fix this, the user config should be merged with the default one.

---
<sup>1</sup> For example: when only the `runtime.language` is set, the version doesn't get displayed in the audio tab anymore. Also the volume selector in the audio tab vanishes because the `runtime.platform` is not set (to `desktop`) anymore.

<sup>2</sup> Other than stated in the documentation, the automatic language selection does not seem to work for me. But this seems to be another issue.

**Comment by alexander-heimbuch** [comment]
thanks for the report, I recently also detected a similar issue with the runtime and date/time related locales. Will investigate :)
