### ISSUE TITLE
The replay button is broken

### ISSUE THREAD

**Issue by jdreesen** [podlove/podlove-web-player#867]
The _replay_ button only flickers a bit after clicking on it, but it does not replay the podcast. 

The browser console displays an `AbortError: The operation was aborted.`

**Comment by alexander-heimbuch** [comment]
Can you give some details about the affected browser?

**Comment by jdreesen** [comment]
Yes of course, sorry!

The problem occurred in Firefox (63.0.3). 

But I just tested it in Chrome (70.0) and it's broken there, too. 
The error message is: `Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

It's broken in my local installation, but also in the demo on https://podlove.org/podlove-web-player/

**Comment by jnnklhmnn** [comment]
Hi!

I had a look at this bug and came up with a solution, you can find my pull request here(https://github.com/podlove/podlove-web-player/pull/881) it was a bug regarding the playstate when the audiofile comes to an end, i had to mangle some state and actions so I hope my proposal suites the needs of the project, I am happy to receive feedback on this.

There is a breaking integration test in the build regarding the controllbar.spec.js which is working fine on my machine, so i could use some help with that if anybody can reproduce it :)
