### ISSUE TITLE
Podlove Player Display Color

### ISSUE THREAD

**Issue by cdestroy** [podlove/podlove-web-player#900]
I loved the podlove player default blue display. All of a sudden it's basically gone and there is no player frame anymore which looks kinda weird/confusing. Anyone else have this issue? Can I customize the player or reset to default? See Screenshot.

![Bildschirmfoto 2019-03-27 um 17 14 53](https://user-images.githubusercontent.com/48997536/55093017-e7cf4780-50b3-11e9-8873-0ebb12fd8b04.png)
[http://xsxm.de/](url)

**Comment by alexander-heimbuch** [comment]
Hmm, looks like the blue is back :D if you have still issues with the color, there should be a configuration available in the publisher.

![Screenshot 2019-03-27 at 18 14 02](https://user-images.githubusercontent.com/7794717/55097445-279a2d00-50bc-11e9-9322-d42fa87df472.png)
