### ISSUE TITLE
Cannot read property 'language' of undefined

### ISSUE THREAD

**Issue by JaegersNet** [podlove/podlove-web-player#903]
Hi,

the podlove-web-player is working fine, but I see the following error message in the JavaScript console in the WordPress backend (Gutenberg Editor):

podlove-web-player.min.js?ver=2.1.0:1 Uncaught TypeError: Cannot read property 'language' of undefined
    at podlove-web-player.min.js?ver=2.1.0:1
    at podlove-web-player.min.js?ver=2.1.0:1
(anonymous) @ podlove-web-player.min.js?ver=2.1.0:1
(anonymous) @ podlove-web-player.min.js?ver=2.1.0:1

**Comment by alexander-heimbuch** [comment]
This repo is for version 4 only, please create this ticket in https://github.com/podlove/podlove-web-player-v2 (but since v2 is only in maintenance mode I wouldn't expect a fix).
