### ISSUE TITLE
Embedded player doesn't work anymore after updating to 

### ISSUE THREAD

**Issue by Susticle** [podlove/podlove-web-player#906]
After updating Podlove Podcast Publisher to version 2.7.24, the embedded player does not work anymore.

An error is shown:

> Benötigte Informationen fehlen
> Zum abspielen des Podcasts fehlen die Referenzen zu den Audiodateien.

Player version is 4.2.4.

**Comment by alexander-heimbuch** [comment]
Already got some reports, I will try to release a fix for this with the next release.
https://community.podlove.org/t/bug-the-embedding-episodes-player-doesnt-work-after-the-last-update/1795/3
