### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by petrk94** [podlove/podlove-web-player#925]
Hello,
I would like to know where I can find the changelog?
I could find here a changelog of one Version:
https://community.podlove.org/t/release-4-5-2/1804

but this is not the whole development history and the last release here on github ist form 2018.

Hope you can help.
Thanks

**Comment by alexander-heimbuch** [comment]
Thats because the project moved to https://github.com/podlove/podlove-ui. Even though I still need to update the changelog process there. (Ticket to keep track: https://github.com/podlove/podlove-ui/issues/136)
