### ISSUE TITLE
Wordpress localization: force German version

### ISSUE THREAD

**Issue by michaeljakob** [podlove/podlove-web-player#933]
How do you force the podcast player (wordpress plugin) to use German as language?

How do I use the files at https://github.com/podlove/podlove-ui/blob/development/apps/player/lang/de.json ?

Podcast Player always shows English text like "Chapters", see the screenshot below:
<img width="973" alt="Screenshot 2020-07-13 22 24 53" src="https://user-images.githubusercontent.com/3597595/87350190-182d4480-c58a-11ea-8105-080241c8fa97.png">

**Comment by 54696d21** [comment]
changing the line in src/utils/runtime.js  `const locale = navigator.language || navigator.userLanguage || 'en-us' to `const locale = 'de-de'` should work`

**Comment by alexander-heimbuch** [comment]
This is a duplicate issue, please see https://github.com/podlove/podlove-ui/issues/574 for an answer.
