### ISSUE TITLE
Emojis not displayed properly

### ISSUE THREAD

**Issue by Guacam-Ole** [podlove/podlove-web-player#935]
[Podlove Player 5]

When the title of the episode contains Emojis they are not displayed properly in the Podlove Web Player.  Example: 
[Episode](https://www.blathering.de/2020/07/blathering-136-%f0%9f%9a%b6-%f0%9f%91%a9-%f0%9f%91%a8-%f0%9f%93%b7-%f0%9f%93%ba/)

The Title displayed is 
![grafik](https://user-images.githubusercontent.com/4692497/88654427-a991d000-d0cd-11ea-9ece-9a2cf7b19cd7.png)

 but should have been

>  Blathering – 136 – 🚶 👩 👨 📷 📺

(tested in firefox, chrome and opera)

**Comment by alexander-heimbuch** [comment]
First of all, the player has moved to a different repo, this only contains the documentation.

The player is totally capable of rendering emojis. In your case the received configuration already contains the encoded emojis:

```
{
  "title: "Blathering - 136 - &#x1f6b6; &#x1f469; &#x1f468; &#x1f4f7; &#x1f4fa;"
}
```

So my guess is that the Publisher already encodes the title.

**Comment by Guacam-Ole** [comment]
It looks like the "&" is encoded as "&amp" which seems to cause the behaviour. The source of the .episode-title element looks like this:

`Blathering - 136 - &amp;#x1f6b6; &amp;#x1f469; &amp;#x1f468; &amp;#x1f4f7; &amp;#x1f4fa;`

but should be without the "amp;" imho

(sorry to bother. Will create a new issue on the new repo instead if this makes more sense)

When switching to the (outdated) "Podlove Web Player 3" the title is displayed correctly
